### ISSUE TITLE
Clicking `<md-button>` within `<md-steppers>` crashes Chrome

### ISSUE THREAD

**Issue by mismith** [vuematerial/vue-material#1612] opened 2018-03-19 04:17 UTC
- Make sure to only create issues for the newest version.

### Steps to reproduce

1. In incognito mode in Chrome 65.0.3325.162 (latest) on macOS 10.13.3 (latest), visit: https://vuematerial.io/components/app/
2. Click the "Steppers" component in the left hand menu (this will navigate you to https://vuematerial.io/components/steppers, but for some reason Chrome cannot load this page directly, maybe a linked bug?)
3. Scroll down to the "Linear Steppers" > "With error handler" section, and click the blue "Continue" button within that example
4. Chrome will hang (your mouse clicks will no longer work, likely your cursor will stay on the pointer/hand)
5. Open Chrome's "Task Manager" from the "Window" menu, and sort by "CPU %", notice how this tab is using >100% CPU.

### Which browser?

- Chrome 65.0.3325.162 (latest)
- macOS 10.13.3 (latest)

### What is expected?

1. no crash/hang
2. https://vuematerial.io/components/steppers and/or https://vuematerial.io/components/steppers/ should load a non-white page

### What is actually happening?

I haven't looked at the source yet, but I'm guessing maybe there is some infinite loop on the click handler of the button or something?

### Reproduction Link

See above.

**Comment by Samuell1** [comment] 2018-03-19 07:21
Duplicate of #1555

**Closed by Samuell1** 2018-03-19 07:21 UTC
