### ISSUE TITLE
[feature request] TimePicker and DateTimePicker

### ISSUE THREAD

**Issue by bigradish** [vuematerial/vue-material#1890] opened 2018-08-05 02:50 UTC
I think TimePicker is useful, and especially DateTimePicker, which combines datepicker and timepicker together. You can refer to https://muse-ui.org/#/en-US/date-input
Thanks.

**Comment by Samuell1** [comment] 2018-08-05 07:57
Duplicate of #1478

**Closed by Samuell1** 2018-08-05 07:57 UTC
