### ISSUE TITLE
I need the vue-material d.ts file, I hope to join as soon as possible.

### ISSUE THREAD

**Issue by CG-man** [vuematerial/vue-material#1928] opened 2018-09-10 03:16 UTC
Oh, I want to get the @types/vue-material ，Do you have this plan?

**Comment by Samuell1** [comment] 2018-09-10 06:16
Duplicate of #662

**Closed** 2018-09-10 07:35 UTC
Labels: duplicated

**Comment by ravindrasinghinbox** [comment] 2019-09-17 00:17
Vue.use(require('vue-material'))
