### ISSUE TITLE
installing 1.0.0-beta4 via npm results in error

### ISSUE THREAD

**Issue by tdondich** [vuematerial/vue-material#1155] opened 2017-11-17 01:44 UTC
### Steps to reproduce

Attempted to install 1.0.0-beta4 via npm:

npm install vue-material@beta --save

### Which browser?

Windows 10 with git bash, npm 3.10.10

### What is expected?

Package should install

### What is actually happening?

> vue-material@1.0.0 postinstall C:\Users\taylo\dev\sketch\node_modules\vue-material
> sh build/git-hooks/install.sh

sh: build/git-hooks/install.sh: No such file or directory

**Comment by ndabAP** [comment] 2017-11-17 05:55
I had the same error. I removed `npm_modules` several times and reinstalled it and at some point it works. Can't explain it.

**Comment by SirCodewright** [comment] 2017-11-17 12:43
FWIW, I have the same issue with the non-beta release (npm install vue-material@1.0.0 --save) on win 10 pro, node 8.1.3, npm 5.0.4, sh from https://sourceforge.net/projects/win-bash/files/. It still fails after multiple cycles of deletion of the `node_modules` folder and reinstallation. Thanks for your great work and thanks in advance for looking into this issue (if you decide to do so).

**Comment by DarkIsDude** [comment] 2017-11-18 15:41
Yes, it's seem `` works.

Here a git to reproduce this issue: https://github.com/DarkIsDude/vue-material-docker.

**Comment by tdondich** [comment] 2017-11-20 14:08
Verified that running: npm install vue-material@beta --save worked after a frustrating amount of time of removing node_modules and doing fresh installs.  Might be safe to close now.

**Comment by Anaphase** [comment] 2017-11-20 20:26
I'm also running into this issue when deploying via CI. `npm install vue-material@beta --save` works fine for installing the package locally, but when running `npm install` in my deployment process (with no node modules installed), the install fails because the vue-material's postinstall is trying to run the non-existent git-hook:

```
npm ERR! vue-material@1.0.0 postinstall: `sh build/git-hooks/install.sh`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the vue-material@1.0.0 postinstall script 'sh build/git-hooks/install.sh'.
```

**Comment by Samuell1** [comment] 2017-11-26 09:15
Looks like @Anaphase found issue. I closing for now, if you get this issue again reopen it.

**Closed by Samuell1** 2017-11-26 09:15 UTC
Labels: needs repro

**Comment by sebbi08** [comment] 2017-12-07 12:53
Just to carify some things npm is doing nothing wrong here. Thats because the version 1.0.0-beta-x will is the beta version of 1.0.0 . Therefor when installing it with somthing like ^1.0.0-beta-4 there the version 1.0.0 will alway be installed. When having a look at `npm view vue-material` you will see the version array: 
`
[ '0.0.1',
     '0.0.2',
     '0.0.3',
     '0.0.4',
     '0.0.5',
     '0.0.6',
     '0.0.7',
     '0.0.8',
     '0.0.9',
     '0.0.10',
     '0.0.11',
     '0.0.12',
     '0.0.13',
     '0.0.14',
     '0.0.15',
     '0.1.0',
     '0.1.1',
     '0.1.2',
     '0.2.0',
     '0.3.0',
     '0.3.1',
     '0.3.2',
     '0.3.3',
     '0.4.0',
     '0.4.1',
     '0.4.2',
     '0.4.3',
     '0.5.0',
     '0.5.1',
     '0.5.2',
     '0.6.0',
     '0.6.1',
     '0.6.2',
     '0.6.3',
     '0.7.0',
     '0.7.1',
     '0.7.2',
     '0.7.3',
     '0.7.4',
     '0.7.5',
     '0.8.0',
     '0.8.1',
     '1.0.0-beta-1',
     '1.0.0-beta-2',
     '1.0.0-beta-3',
     '1.0.0-beta-4',
     '1.0.0-beta-5',
     '1.0.0-beta-6',
     '1.0.0-beta-7',
     '1.0.0' ]
`
^ in front of an version number will always update to the the highes minor release.

so this should be fixable with using something like 1.0.1-beta-x as next version

**Comment by Samuell1** [comment] 2017-12-11 07:25
@Last-Order or just `beta`

**Comment by simonepri** [comment] 2018-03-01 00:32
as @Last-Order 
Changing 
`"vue-material": "^1.0.0-beta-8"`
to
`"vue-material": "1.0.0-beta-8"`
solves the problem
