### ISSUE TITLE
FAB not fixed on surface, but floats with scrolling content

### ISSUE THREAD

**Issue by jan-johansson-mr** [vuematerial/vue-material#1723] opened 2018-05-12 12:08 UTC
### Steps to reproduce
1. Create a simple md-app (as an example), with scrolling content enabled
2. Add FAB button to application
3. Scroll surface

### Which browser?
Chrome

Vue 3.0.0-beta.10, Vue material 1.0.0-beta-8, Linux, Chrome (Version 66.0.3359.139)

### What is expected?
FAB will stay put in one place, regardless of scrolling content

### What is actually happening?
FAB moves with the surface and can leave visible area if scrolled out of view

### Reproduction Link
https://codepen.io/anon/pen/ELLzMQ

**Comment by Samuell1** [comment] 2018-05-12 12:11
Duplicate of #1369

**Closed by Samuell1** 2018-05-12 12:11 UTC
