### ISSUE TITLE
value should be updated to interpolation expression

### ISSUE THREAD

**Issue by simongcc** [vuematerial/vue-material#1672] opened 2018-04-08 05:41 UTC
I have asked Node-sass before about [CSS custom properties(variables) not rendered correctly in libsass 3.5.2](https://github.com/sass/libsass/issues/2620)

According to the answer

```
Sass is not allowed to evaluate the values of custom properties. The one exception is string interpolation.
```

The following statement 
```
:root {
    @each $type, $value in $palette {
      --md-theme-#{$name}-#{$type}: $value
    }
  }
```

should be written as
```
:root {
    @each $type, $value in $palette {
      --md-theme-#{$name}-#{$type}: #{$value}
    }
  };
```

So that in newer version of node-sass could be rendered properly.
I have tried this, Node-sass 4.7.2 is still support the older writing style, and in 4.8.3, only the newer writing style will be rendered correctly or the output will be a text '$value'.

**Comment by Samuell1** [comment] 2018-04-08 09:02
Its already fixed in dev.

Duplicate of #1619

**Closed by Samuell1** 2018-04-08 09:02 UTC
