### ISSUE TITLE
 [mdInput] <md-input type="number"> - wrong cursor position

### ISSUE THREAD

**Issue by Akiyamka** [vuematerial/vue-material#600] opened 2017-03-10 12:21 UTC
when used `type="number"` attempt input some letter will lead to a shift the cursor up
![image](https://cloud.githubusercontent.com/assets/6587585/23795169/1984aad8-05a5-11e7-8b8b-b351eb045b46.png)
Reproduce: https://jsfiddle.net/akiyamka/rykkr0xj/4/

**Comment by Samuell1** [comment] 2017-03-12 10:59
Browser? In firefox is okay

![obrazok](https://cloud.githubusercontent.com/assets/3110002/23831145/46bd5028-071b-11e7-98ca-bb5ef0b1bcb5.png)

**Comment by craigvantonder** [comment] 2017-03-12 17:12
I tested in Firefox and Chrome, works fine for me. Is it not some other css include that is messing this up maybe?

What browser and device is this issue happening in?

**Comment by wopian** [comment] 2017-03-12 18:15
Cannot reproduce on stock Chrome 59 or 57

Can reproduce on stock Chrome 56

https://gfycat.com/ClumsyFemaleGartersnake

**Comment by Akiyamka** [comment] 2017-03-12 18:37
reproduce on Chrome 56.0 win 10, Firefox 51.0.1 - type does not work, you can enter the letters regardless of type

**Comment by marcosmoura** [comment] 2017-03-21 00:48
I couldn't reproduce this issue. Can you confirm if you solved using another thing?

**Comment by Samuell1** [comment] 2017-11-23 20:20
Closing this issue as our focus is on the new 1.0.0 version.

**Closed by Samuell1** 2017-11-23 20:20 UTC
Labels: needs repro
