### ISSUE TITLE
Internet Explorer issue with compatibility

### ISSUE THREAD

**Issue by sangemi** [vuematerial/vue-material#1948] opened 2018-10-12 03:27 UTC
I installed vuematerial/nuxtjs 
bue in nuxtjs github page, I cannot find issues page.

I am using
> md-stepper, md-card, md-tooltip, md-select, md-snackbar
> and vue-smooth-dnd

in my page. It worked well in chrome but in IE,

> **object doesn't support property or method 'values'**

I think this bugs is related with https://github.com/vuematerial/vue-material/issues/165

**Comment by zapping** [comment] 2018-10-12 13:03
Can you check this #1526

**Comment by Samuell1** [comment] 2018-12-25 13:03
Duplicate of #1526

**Closed by Samuell1** 2018-12-25 13:03 UTC
