### ISSUE TITLE
[SCSS] md-hide-medium-and-up and md-hide-small both hidden at the same time

### ISSUE THREAD

**Issue by nahtnam** [vuematerial/vue-material#631] opened 2017-03-23 01:56 UTC
### Steps to reproduce
1. Go to http://codepen.io/nahtnam/pen/ZeoJEv
2. Adjust the browser so it's 944px wide

Both the right menu button and the left sidenav icon are hidden at the same time making the menus inaccessible.
### Which browser?

I'm using Vue `2.2.4`, Vue Material `0.7.1`, `macOS Sierra`, and Chrome `56.0.2924.87`
### What is expected?
At least one of the buttons should be showing, either the small one or the medium and up one.
### What is actually happening?

Both buttons are hidden.
### Reproduction Link

http://codepen.io/nahtnam/pen/ZeoJEv

**Comment by rascoop** [comment] 2017-03-23 21:38
I think the problem is in the mixins.scss.
The **max-width** should be the breakpoint not the breakpoint - 16px or 17px

@mixin layout-xsmall {
  @media (**max-width: #{$breakpoint-xsmall}**) {
    @content;
  }
}

@mixin layout-small {
  @media (**max-width: #{$breakpoint-small - 16px}**) {
    @content;
  }
}

@mixin layout-medium {
  @media (**max-width: #{$breakpoint-medium - 16px}**) {
    @content;
  }
}

@mixin layout-large {
  @media (**max-width: #{$breakpoint-large - 17px}**) {
    @content;
  }
}

**Comment by DavidBradbury** [comment] 2017-04-06 16:14
Yeah, I'm having a similar issue with md-hide-small-and-up - That code looks ridiculous. 

`@mixin layout-small-and-up {
  @media (min-width: #{$breakpoint-small - 300px}) {
    @content;
  }
}`

Why is there hardcoded pixel values there?  Small and up would be -360 if you did want to hardcode a value... But it should be using the actual breakpoints to avoid unpredictable behavior around those points.

**Comment by pablohpsilva** [comment] 2017-05-14 22:11
Hello guys! How do you do?
The `16px` on those breakpoints have a reason:
> Desktop breakpoints are 16dp below the listed values to accommodate variations in browser chrome.

Let's talk about the breakpoints, shall we? Well, we have these breakpoints: 
```scss
$breakpoint-xsmall: 600px !default;
$breakpoint-small: 960px !default;
$breakpoint-medium: 1280px !default;
$breakpoint-large: 1920px !default;
```

Based on [Material Design Devices Screen sizes](https://material.io/devices/), the breakpoints, in my opinion, should be:
```scss
$breakpoint-xxsmall: 136px !default; // smallest watch screen
$breakpoint-xsmall: 320px !default; // smallest device screen
$breakpoint-small: 600px !default;
$breakpoint-medium: 960px !default;
$breakpoint-large: 1280px !default;
$breakpoint-xlarge: 1920px !default;
```

OK, if that in mind, and considering the `16px` tip, we should have the following `md-hide-*` variations:
```scss
@mixin layout-xsmall {
  @media (max-width: #{$breakpoint-xsmall}) {
    @content;
  }
}

@mixin layout-small {
  @media (max-width: #{$breakpoint-small - 16px}) {
    @content;
  }
}

@mixin layout-medium {
  @media (max-width: #{$breakpoint-medium - 16px}) {
    @content;
  }
}

@mixin layout-large {
  @media (max-width: #{$breakpoint-large - 17px}) {
    @content;
  }
}

@mixin layout-xlarge {
  @media (min-width: #{$breakpoint-large - 16px}) {
    @content;
  }
}

// Small and up INCLUDES the size on the breakpoint.
// E.g: md-hide-small-and-up: includes small and beyond 

@mixin layout-xsmall-and-up {
  @media (min-width: #{$breakpoint-xxsmall + 16px}) {
    @content;
  }
}

@mixin layout-small-and-up {
  @media (min-width: #{$breakpoint-xsmall + 16px}) {
    @content;
  }
}

@mixin layout-medium-and-up {
  @media (min-width: #{$breakpoint-small + 16px}) {
    @content;
  }
}

@mixin layout-large-and-up {
  @media (min-width: #{$breakpoint-medium + 16px}) {
    @content;
  }
}
```

> // Small and up INCLUDES the size on the breakpoint.
> // E.g: md-hide-small-and-up: includes small and beyond 

That's why the `@media (min-width: #{$breakpoint-small - 300px})` is not ridiculous and it makes sense in that way. But it can be improved. What do you think @marcosmoura @DavidBradbury @nahtnam ?

**Comment by capttrousers** [comment] 2017-06-17 21:51
I'm hitting a similar issue, not sure if it's by design or a type on the css, but for md-hide-small-and-up combined with md-hide-xsmall theres a 60px gap from screensize width @600px - 660px where the xsmall hidden div is showing up due to this breakpoint:

```
@media (min-width: 660px)
.md-hide-small-and-up {
    display: none;
}
```

**Comment by tote88** [comment] 2017-06-19 14:25
I'm experiencing the same issue as @capttrousers . There is a gap between 600px and 660px where hide-xsmall and hide-small-and-up md-layouts are both shown.

**Comment by DavidBradbury** [comment] 2017-06-19 14:46
The ridiculousness is not in the values themselves, but using hardcoded values and leaving them without any comments or documentation. I understand people are putting these things together in their free time, but that isn't really a reason to make things harder on all the other collaborator's. That's just lazy. Set a variable, explain what it does, and then use that in other areas instead of copying and pasting values.

**Comment by Samuell1** [comment] 2017-11-23 20:33
Closing this issue as our focus is on the new 1.0.0 version.

**Closed by Samuell1** 2017-11-23 20:33 UTC
Labels: improvement
