### ISSUE TITLE
[MdFile] Clicking on the file input field in NW.js triggers endless file selection dialog box

### ISSUE THREAD

**Issue by toyssamurai** [vuematerial/vue-material#1677] opened 2018-04-11 17:19 UTC
### Steps to reproduce
Download the latest NW.js for Windows, added a simple HTML file to test the File Input Field of Vue Material. Click on the File Input Field.

### Which browser?
NW.js 64 bit on Windows 10

### What is expected?
Selecting a file or canceling the selection will close the file selection dialog box

### What is actually happening?
The file selection dialog box will keep coming up no matter what you do. The only thing that works is to kill the app.

**Comment by Samuell1** [comment] 2018-04-11 17:25
Can you test normal file input if its same? and try to focus on it with action button that triggers click on it `this.$refs.NAME.click()`

Because i think this is not our issue but issue in NW.js

**Comment by toyssamurai** [comment] 2018-04-11 20:02
Normal file input has not such problem. In fact, when I looked up the actual file input behind the Material File Input, then triggered a click thru code, the dialog box will be closed like normal. So, it looks like the problem only happens when the Material File Input is interacted directly through the UI.

**Comment by Samuell1** [comment] 2018-04-12 06:26
Yes but i cant reproduce it in normal browser. It works fine in Chrome and Firefox.

**Comment by toyssamurai** [comment] 2018-04-13 15:03
I filed an issue on NWjs's issue tracker. I do want to point out that the nature of a bug like this one is hard to pinpoint which side causes the problem. If we consider NW as a browser, and Vue Material/Vue a third party library, traditionally Javascript libraries would often work around bugs like this one until the browser is fixed -- I am not suggesting that this bug needs to be "fixed" because the situation is different as NW is not a widely used "browser' like Firefox and Chrome, but nevertheless it's something to keep in mind.

**Comment by Samuell1** [comment] 2018-04-13 15:55
If you find a time best will be to provide reproduction repository where we can test this bug.

**Comment by Samuell1** [comment] 2018-05-03 07:44
Closing for now. If you find more info reply here and i reopen it.

**Closed by Samuell1** 2018-05-03 07:44 UTC

**Comment by 0xADD1E** [comment] 2018-05-22 03:26
Able to reproduce (god only knows how) in FF 60.0.1 on Debian testing, but I suspect it could be a larger issue. 

What I suspect is happening is that returning from the file picker triggers another focus event. This is backed by the fact that spamming esc will drop focus from the component, and break the loop (though I haven't actually been able to see the events showing up). 

Will update when I get the chance to triage more, in the mean time this should be reopened

**Comment by 0xADD1E** [comment] 2018-05-22 18:02
This does indeed seem to be the case, as changing to `@click` resolves the issue for me. @toyssamurai can you test this fix in PR #1769

**Comment by Wrongness** [comment] 2019-03-26 16:43
on Chrome 73, on Ubuntu 18.04
to reproduce just visit yours page: https://vuematerial.io/components/file
and try to cancel file select window, also often same happens when selecting file

**Comment by 0xADD1E** [comment] 2019-03-26 23:25
Do you know if this affects the dev branch that has the focus vs click event fixes?

**Comment by ruanltbg** [comment] 2019-05-02 04:00
@0xADD1E this is still happening here: https://codesandbox.io/s/p3xoqmm68x?module=App.vue
Same as @Wrongness.

**Comment by Samuell1** [comment] 2019-05-02 06:09
@ruanltbg but you need to recompile dev branch, because fix was pushed there not in master

**Comment by Thyiad** [comment] 2019-05-02 06:23
as for me, i build a package named @thyiad/vue-material

**Comment by sunyatasattva** [comment] 2019-07-23 22:20
The fix has been merged into `dev` more than a year ago, any reason why it is not in `master`?
