### ISSUE TITLE
Error, on datepicker dialog open

### ISSUE THREAD

**Issue by walkerz88** [vuematerial/vue-material#1399] opened 2018-01-14 16:43 UTC
Hi! When i open md-datepicker, or select date, i've got an error in console: 
[Vue warn]: Duplicate keys detected: '1'. This may cause an update error.

code: 
`<md-datepicker v-model="event.date_end"/>`

event: {
    date_end: null
}

But datepicker still works fine, just show this error

Please see screenshot: http://prntscr.com/i0bpv3

**Comment by Samuell1** [comment] 2018-01-14 18:10
Duplicate of #1376

**Closed by Samuell1** 2018-01-14 18:10 UTC
