### ISSUE TITLE
Console errors

### ISSUE THREAD

**Issue by CrixuAMG** [vuematerial/vue-material#985] opened 2017-08-18 10:03 UTC
[screenshot](http://imgur.com/AgH777i)

Template:
```
<template>
    <div>
        <md-layout md-gutter>
            <md-layout>
                <h1>Welcome to FreshProject!</h1>

                <router-link :to="{name: 'landing-page'}">Go to landing</router-link>

                <p v-if="isCloning">Cloning...</p>

                <div>
                    <h2>Create or clone a repository</h2>

                    <md-input-container>
                        <label>Repo author</label>
                        <md-input v-model="author"></md-input>
                    </md-input-container>

                    <md-input-container>
                        <label>Repo name</label>
                        <md-input v-model="repo"></md-input>
                    </md-input-container>

                    <md-checkbox md-theme="default" id="npm" name="npm" v-model="npm" class="md-primary">
                        NPM install?
                    </md-checkbox>

                    <md-checkbox md-theme="default" id="composer" name="composer" v-model="composer" class="md-primary">
                        Composer install?
                    </md-checkbox>

                    <md-checkbox md-theme="default" id="new-project" name="new-project" v-model="newProject"
                                 class="md-primary">
                        New project?
                    </md-checkbox>

                    <md-button class="md-raised md-primary" :disabled="!repo || isCloning" @click="createRepo()">
                        Clone repo
                    </md-button>
                </div>
            </md-layout>
        </md-layout>
    </div>
</template>
```

**Comment by zapping** [comment] 2017-08-23 07:25
The error log shows vuejs cannot find the `useTheme` function in `beforeMount` hook. It's a function used in vue-material to load/set the theme as in `this.$material.useTheme()`. You need to make sure that:

- all the necessary imports are given
- the vue-material.css is imported
- vue-material plugin in initialized with Vue.use()

 in your script also and not just the template as per http://vuematerial.io/#/getting-started . You can also refer #11 for further info.

In case if you still have issues please share the script files too.

**Comment by waratah** [comment] 2017-09-22 06:48
have a problem with my themes and I suddenly got this.

'background' is not a valid item in a theme and it gives this message.  Error in callback for watcher "styles": "TypeError: Cannot read property '500' of undefined"

default: {
primary: 'blue',
accent: 'pink',
background: 'rgb( 28,45,63 )'
},

Preferred option: 'background is not valid in a theme' error.

Now I have to figure out how theming works so I can apply it logically.

**Comment by zapping** [comment] 2017-09-25 03:54
You will need to use the [material color palettes](https://material.io/guidelines/style/color.html#color-color-palette) to define your colors.

default: {
primary: 'blue',
accent: 'pink',
background: {color:'grey' , hue:900)
},

More details can be had from the theme doc page http://vuematerial.io/#/themes/configuration

**Comment by waratah** [comment] 2017-09-27 10:16
The issue is that the code references a palette name that is undefined.   I will have to work out a pull request for this one.

PS: Using typescript definitions helped a lot for this.

**Comment by Samuell1** [comment] 2017-11-23 22:10
Closing this issue as our focus is on the new 1.0.0 version.

**Closed by Samuell1** 2017-11-23 22:10 UTC
