### ISSUE TITLE
"Cannot read property 'options' of undefined" when passing route to md-list-item

### ISSUE THREAD

**Issue by franciscohanna92** [vuematerial/vue-material#1980] opened 2018-12-02 01:54 UTC
I have the following template:

```html
<md-app-drawer :md-active.sync="menuVisible">
  <md-list>
    <md-subheader>Sismos</md-subheader>
    <md-list-item to="/" @click="menuVisible = false">
      <md-icon>list</md-icon>
      <span class="md-list-item-text">Go to list</span>
    </md-list-item>
  </md-list>
</md-app-drawer>
```
When I open the app in the broswer the following exceptionis raised:

```
TypeError: Cannot read property 'options' of undefined
    at exports.default (vue-material.js?2e0c:998)
    at createListComponent (vue-material.js?2e0c:9569)
    at render (vue-material.js?2e0c:9602)
    at renderWithStyleInjection (vue-material.js?2e0c:177)
    at createFunctionalComponent (vue.esm.js?efeb:4060)
    at createComponent (vue.esm.js?efeb:4250)
    at _createElement (vue.esm.js?efeb:4420)
    at createElement (vue.esm.js?efeb:4357)
    at vm._c (vue.esm.js?efeb:4489)
    at Proxy.render (eval at ./node_modules/vue-loader/lib/template-compiler/index.js?{"id":"data-v-7ba5bd90","hasScoped":false,"transformToRequire":{"video":["src","poster"],"source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/App.vue (app.js:1161), <anonymous>:57:19)
```
If I remove the `to="/"` from `md-list-item`, it works fine

I'm using `vue 2.5.2`, `vue-material 1.0.0-beta-10.2` and `vue-router 3.0.2`

**Comment by aburai** [comment] 2018-12-03 14:14
relates to #1977

**Comment by Samuell1** [comment] 2018-12-18 08:18
Duplicate of #1977

**Closed by Samuell1** 2018-12-18 08:18 UTC
