### ISSUE TITLE
Getting started documentation doesn't work

### ISSUE THREAD

**Issue by RichardJECooke** [vuematerial/vue-material#1367] opened 2018-01-03 22:59 UTC
### Steps to reproduce

Follow the website: https://vuematerial.io/getting-started

```
import Vue from '../node_modules/vue/dist/vue';
import VueRouter from 'vue-router';
import { MdButton, MdContent, MdTabs } from '../node_modules/vue-material/dist/components';
import '../node_modules/vue-material/dist/vue-material.min.css';
```

Get the error on the page:

```
Uncaught ReferenceError: regeneratorRuntime is not defined
    at 5240b134b1a50fceccaa505b637d71e3.js:20521
    at Object.defineProperty.value (5240b134b1a50fceccaa505b637d71e3.js:20521)
    at t (5240b134b1a50fceccaa505b637d71e3.js:20521)
    at Object.defineProperty.value (5240b134b1a50fceccaa505b637d71e3.js:20521)
    at t (5240b134b1a50fceccaa505b637d71e3.js:20521)
    at Object.defineProperty.value (5240b134b1a50fceccaa505b637d71e3.js:20521)
    at t (5240b134b1a50fceccaa505b637d71e3.js:20521)
    at Object.defineProperty.value (5240b134b1a50fceccaa505b637d71e3.js:20521)
    at t (5240b134b1a50fceccaa505b637d71e3.js:20521)
    at Object.defineProperty.value (5240b134b1a50fceccaa505b637d71e3.js:20521)
```

### Which browser?

Latest Chrome

**Comment by Samuell1** [comment] 2018-01-04 07:21
Duplicate of #1182

**Closed by Samuell1** 2018-01-04 07:21 UTC
