### ISSUE TITLE
clone master code and install, but when npm run dev somethings error

### ISSUE THREAD

**Issue by Harveytwo** [vuematerial/vue-material#657] opened 2017-04-01 03:43 UTC
> vue-material@0.7.1 dev C:\workRelated\code\eleme\vue-material
> babel-node build/server/index.js --presets es2015,stage-0
I clone master code, and install all packages. But when I try to use sudo npm run dev, there are something error. 

module.js:471
    throw err;
    ^

Error: Cannot find module 'core-js/library/fn/get-iterator'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\workRelated\code\eleme\vue-material\node_modules\.6.23.0@babel-runtime\core-js\get-iterator.js:1:93)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by pablohpsilva** [comment] 2017-04-09 15:24
Hello @Harveytwo ! How do you do?

You're running code using super user (sudo). Don't do it. Like... Ever. 
Install your node & npm without super user privileges as much as you can.

I'm using Yarn as a substitute of NPM and I'm loving it! You should too.

I tried to replicate the issue you're having and I was unable to do so. I think the issue is the sudo command.

**Comment by Morgul** [comment] 2017-06-21 15:44
I'm going to close this. @Harveytwo if you're still having issues, please reopen. :smile:

**Closed by Morgul** 2017-06-21 15:44 UTC
Labels: question
