### ISSUE TITLE
[MdAutocomplete] Selecting before typing doesn't work

### ISSUE THREAD

**Issue by emman27** [vuematerial/vue-material#1656] opened 2018-04-02 06:46 UTC
### Steps to reproduce
Basically any autocomplete

### Which browser?
Chrome 65, Ubuntu 16.04

### What is expected?
Selecting an option from an autocomplete should *just work*

### What is actually happening?
If nothing is typed into the box, selecting an item doesn't actually do anything.

### Reproduction Link
![vm-autocomplete-bug](https://user-images.githubusercontent.com/6295583/38186228-681ae458-3684-11e8-8769-7089aa2a78fd.gif)

https://codesandbox.io/s/l28mppv53z

**Comment by Y0hy0h** [comment] 2018-04-02 16:39
Confirmed using repro link on Windows 10 with Firefox 59.0.2 and Chrome 65.0.3325.181.

@emman27, if you'd like to you can make the following additions to your description, for it to be slightly quicker to understand: ;)
### Steps to reproduce
1. Add a `MdAutocomplete` with at least one entry in `:md-options`.
2. Focus the text input and select one of the options.

### Which browser?
Firefox 59.0.2 (Windows 10)
Chrome 65 (Ubuntu 16.04, Windows 10)

**Comment by thecrazything** [comment] 2018-04-05 12:32
I found it sometimes doesn't work even after typing if using `:md-open-on-focus="false"`. Typing one letter, clicking the remove button and then selecting works as long as the input field loses focus.

## Steps to reproduce

1. Add a `MdAutocomplete` with at least one entry and the property `:md-open-on-focus="false"` 
2. Focus on the text input, type one letter and select one of the options remaining. It will not select.
3. Focus on the text input and type two letters directly after each other, select now works.

## Which browser?
Chrome 65 (Windows 10)

**Comment by Samuell1** [comment] 2018-04-05 13:24
It can be because of this https://github.com/vuematerial/vue-material/pull/1665

**Comment by Samuell1** [comment] 2018-04-11 12:19
I tested it in DEV and it works. Closing issue for now.

**Closed by Samuell1** 2018-04-11 12:19 UTC
Labels: bug

**Comment by canyoudev** [comment] 2018-05-01 21:07
I have the same issue. It doesn't select before I begin to type. If there's any input - then it selects. Just like on this GIF. 

Is it possible to fix it? Where's the solution? Why is this closed?

**Comment by canyoudev** [comment] 2018-05-01 21:09
@emman27 did you find the solution?

**Comment by canyoudev** [comment] 2018-05-01 21:29
I just looked into source code, and looks like you messed with package. The content of `MdMenuContent.vue` is broken. They are different than on this GitHub. I tried to build `vue-material` but I can't `Error: Cannot find module build/local`

Too many bugs for such a good looking project. That's very unfortunate.

**Comment by emman27** [comment] 2018-05-02 00:02
Never managed to find the solution to this one. Unfortunately I ended up not using this library for production as my projects were time sensitive.

**Comment by Samuell1** [comment] 2018-05-02 06:18
@canyoudev @emman27 solution is solved in dev

**Comment by Y0hy0h** [comment] 2018-05-02 17:53
@canyoudev You can specify a Git repo including a branch or commit hash as the version in the `package.json`. See the [documentation](https://docs.npmjs.com/files/package.json#github-urls).

So in this case you would specify something like
```
...
"vue-material": "vuematerial/vue-material#baf6a14030c1f57cc77e1751fba424ef11dfe0e6",
...
```

baf6a14030c1f57cc77e1751fba424ef11dfe0e6 is the latest commit. Specifying that instead of the `dev` branch (using `"vuematerial/vue-material#dev"`) has the benefit that everyone will always `npm install` the same version. With `dev`, in the future someone might pull a version that is different from yours and debugging will be a nightmare ("It works on my machine.")  
You can still update the commit hash whenever you want, so you can easily upgrade, but still have control.
