### ISSUE TITLE
[MdDatePicker] Dialog stretches out of the page.

### ISSUE THREAD

**Issue by zapping** [vuematerial/vue-material#1811] opened 2018-06-08 15:25 UTC
When you add a Datepicker component to a Drawer the Datepicker dialog stretches out of the page. If you cancel the dialog and try to open the Datepicker again it won't be visible again. This happens only when its included in a Drawer but when its added directly to a page it works fine without any issues.

This issue has popped up after the 1.0-beta-10 release. It was working fine with the 1.0-beta-8 release. The problem seems to be with values of the top and height attributes set to the Datepicker.

![datepickerissue](https://user-images.githubusercontent.com/4123026/41166312-7064570e-6b2f-11e8-8f1e-62d0351c5c52.PNG)

 Please check this code pen https://codepen.io/zapping/pen/gKLePd . Do click on the menu icon to open the Drawer which has a Datepicker component.

**Comment by Samuell1** [comment] 2018-06-11 12:18
Duplicate of #1794

**Closed by Samuell1** 2018-06-11 12:18 UTC
