### ISSUE TITLE
[MdListItem] Error when using 'to' prop for router-link

### ISSUE THREAD

**Issue by davidsbond** [vuematerial/vue-material#2018] opened 2019-02-12 21:50 UTC
### Steps to reproduce

I have a Vue component that creates an `MdList` dynamically with `MdListItems` that are populated via an array:

```vue
<template>
  <MdList>
    <MdListItem
      v-for="item in items"
      :key="item.text"
      :to="item.route"
    >
      <MdIcon>{{ item.icon }} </MdIcon>
      {{ item.text }}
    </MdListItem>
  </MdList>
</template>
```

I populated the `items` array like so:

```json
[{"route":"/sites","text":"Sites","icon":"business"}]
```
### Which browser?

Chromium: Version 71.0.3578.98 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)
Vue version 2.5.17
Vue material version 1.0.0-beta-10.2

### What is expected?

The list item renders using the router links

### What is actually happening?

This error in my developer console and the list item does not render:

```
[Vue warn]: Error in render: "TypeError: Cannot read property 'options' of undefined"

found in

---> <SideBar> at src/components/SideBar.vue
       <App> at src/App.vue
         <Root>
```

And:

```
TypeError: Cannot read property 'options' of undefined
    at exports.default (vue-material.js?43f9:998)
    at createListComponent (vue-material.js?43f9:9569)
    at render (vue-material.js?43f9:9602)
    at renderWithStyleInjection (vue-material.js?43f9:177)
    at createFunctionalComponent (vue.runtime.esm.js?2b0e:3027)
    at createComponent (vue.runtime.esm.js?2b0e:3200)
    at _createElement (vue.runtime.esm.js?2b0e:3385)
    at createElement (vue.runtime.esm.js?2b0e:3322)
    at vm._c (vue.runtime.esm.js?2b0e:3454)
    at eval (eval at ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"48deef1b-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/SideBar.vue?vue&type=template&id=3eca7188&scoped=true& (app.js:1334), <anonymous>:11:14)
```

**Comment by davidsbond** [comment] 2019-02-12 21:59
I was able to work around this by changing the `vue-router` depdendency to `3.0.1`. However, I also had to change `RouterView` to `router-view`

**Comment by Samuell1** [comment] 2019-02-14 07:08
Duplicate of #1977

**Closed by Samuell1** 2019-02-14 07:08 UTC
