### ISSUE TITLE
Autocomplete component, options with Objects doesn't display selected value

### ISSUE THREAD

**Issue by pytsekas** [vuematerial/vue-material#1693] opened 2018-04-26 11:50 UTC
### Steps to reproduce
[Autocomplete component](https://vuematerial.io/components/autocomplete/), Async Options section example

### Which browser?

Chrome

### What is expected?

After selecting autocomplete value, input should display needed object attribute

### What is actually happening?

After selecting autocomplete value, input displays "[object Object]"

### Reproduction Link

[Autocomplete component](https://vuematerial.io/components/autocomplete/), Async Options section example

**Comment by Samuell1** [comment] 2018-04-26 11:53
Duplicate of #1243

**Closed by Samuell1** 2018-04-26 11:53 UTC
