### ISSUE TITLE
z-index in dialog

### ISSUE THREAD

**Issue by vrnehot** [vuematerial/vue-material#1421] opened 2018-01-22 09:05 UTC
### Steps to reproduce
Open the dialog, open the drop-down menu of the select inside the dialog

### Which browser?
chrome 63.0.3239.132

### What is expected?
The drop-down menu of the select inside the dialog box will be above the dialog

### What is actually happening?
drop-down menu of the select within the dialog, under the dialog

**Comment by Samuell1** [comment] 2018-01-22 09:28
Please first search in issues, then create new issue. Duplicate of #1149

**Closed by Samuell1** 2018-01-22 09:28 UTC
