### ISSUE TITLE
New vue material (1.0 beta) website display problems | chrome , IE , edge

### ISSUE THREAD

**Issue by C0d1ngJammer** [vuematerial/vue-material#1151] opened 2017-11-16 21:25 UTC
Hello Vue-material community,

I heard about the new Vue-Material version and had to test it, awesome! 
The old site worked fine, but on the new site my browsers kinda mess it up. 

If you need more information or some clarification, tell me.
This is my first Github post :)

### Steps to reproduce

Go  to https://vuematerial.io/ via chrome and you should see some wired flicker behavior as below (.gif):
![vuematerial_chome](https://user-images.githubusercontent.com/10685463/32915904-b8c95d9c-cb1a-11e7-8180-49c9b429a3b0.gif)
This works sometimes and sometimes not. 

The next one occourse in microsoft edge, the "background" is blue and looks like someone selected the elements: 
![vuematerial_edge](https://user-images.githubusercontent.com/10685463/32915982-f474f52c-cb1a-11e7-814a-6cfd7925e843.PNG)

In Internet Explorer (latest version?) I get no result -> empty page. But this might just be a polyfill problem. With the error msg "Promies" is undefined.

In all 3 browsers I cleaned my cache/cookies, disabled extensions and used Incognito mode with the same result. Latest version of Firefox works perfectly fine! 

### Which browser?

Chrome version:
62.0.3202.94 (64bit)

Edge version: 
Microsoft Edge 40.15063.674.0
Microsoft EdgeHTML 15.15063

Internet Explorer version:
11.6.74.15.063.0

Using windows 10 pro

**Comment by Oduig** [comment] 2017-11-18 21:56
+1 I have the same problem. It's great to see such active development, though in my humble opinion the old look & feel was more vibrant and clear. I suspect some of the styling hasn't been done yet?

**Comment by marcosmoura** [comment] 2017-11-18 23:18
This is due a transition bug. I already know what is happening. Fix will be released soon!

**Comment by timoschwarzer** [comment] 2017-11-21 10:35
Fixed by https://github.com/vuematerial/vue-material/commit/d292d800a411eb51587591ca15b3efcbf4018354 (at least on Chrome)

**Closed** 2017-11-24 15:03 UTC
Labels: bug, documentation

**Comment by C0d1ngJammer** [comment] 2017-11-24 18:49
True, transition in chrome is fixed. In Microsoft Edge still the same.

**Comment by amenak77** [comment] 2017-12-19 09:17
Hi vue-material community,
I'm Amenak77 part of Freedomotic team (www.freedomotic.com); we are developing a new vue based client for our IoT framework and we are quite satisfied by the results; 
![vue_mat_err_4](https://user-images.githubusercontent.com/13914556/34149430-5154a802-e4a5-11e7-902c-d6b53cfac99a.jpg)
here our repository  https://github.com/freedomotic/fd-vue-webapp  Our aim is replace our old polymer based client with vue, but at the moment, we have same C0s1ngJammer problem with Edge
![vue_mat_err](https://user-images.githubusercontent.com/13914556/34149331-08de4b32-e4a5-11e7-9da6-918f09769463.jpg)
![vue_mat_err_2](https://user-images.githubusercontent.com/13914556/34149357-1ae9e6c4-e4a5-11e7-84c2-6057b357757f.jpg)
No problems with Chrome and Firefox
I know that the issue is closed and I don't want to annoy anyone, but "multi browser compatibility" is one of main chiose parameters about vue, and we are a little worried.
Best regards, Amenak77

**Comment by Samuell1** [comment] 2017-12-19 09:23
@amenak77 That is bug in Edge we cant do anything with that, only you can update to new Edge version https://github.com/vuematerial/vue-material/issues/1224#issuecomment-349959771

**Comment by amenak77** [comment] 2017-12-19 09:25
PD the first picture is normally represented with Chrome, but note how Edge a strong red background component in picture 2 and 3; problem number 2 reported by C0d1ngJammer, but we have the red hulk version :)

**Comment by amenak77** [comment] 2017-12-19 09:26
@Samuell1 do you know for sure that upgrading Edge the bug is fixed?

**Comment by Samuell1** [comment] 2017-12-19 09:27
@amenak77 yes look at that issue, i have version 41 and its fine

**Comment by amenak77** [comment] 2017-12-19 09:28
@Samuell1 thank you very much; I'll do it ASAP

**Comment by amenak77** [comment] 2017-12-19 13:06
Hi guys,
after upgrade to Microsoft Edge 41.16299.15.0 e Microsoft EdgeHTML 16.16299, all fixed
![vue_mat_fix](https://user-images.githubusercontent.com/13914556/34158452-ca6ad4bc-e4c5-11e7-82e3-a7370c037382.jpg)

@Samuell1 thanks again. Best regards, Amenak77
