### ISSUE TITLE
[md-select] item selection in md-select is behind md-dialog window

### ISSUE THREAD

**Issue by Kusumoto** [vuematerial/vue-material#1434] opened 2018-01-24 07:19 UTC
### Steps to reproduce
Select the md-select in md-dialog.

### Which browser?
"vue": "^2.5.2",
"vue-material": "1.0.0-beta-7",
Firefox and Google Chrome

### What is expected?
Menu selection item in md-select is show in front of the md-dialog.

### What is actually happening?
Select item in md-select after selection menu render, menu item is show behind the dialog window.

### Reproduction Link

https://codepen.io/anon/pen/ZvNWgL

<img width="937" alt="screen shot 2561-01-24 at 13 39 40" src="https://user-images.githubusercontent.com/1545085/35319245-8fb03250-0111-11e8-9222-a2823ac4af28.png">

**Comment by Samuell1** [comment] 2018-01-24 07:53
Duplicate of #1149

**Closed by Samuell1** 2018-01-24 07:53 UTC
