### ISSUE TITLE
Import components on demand, failed to do so, an error

### ISSUE THREAD

**Issue by FDLFDL** [vuematerial/vue-material#1396] opened 2018-01-12 03:53 UTC
According to the example did not succeed
![51q m5_9 9 a5skw_w i hg](https://user-images.githubusercontent.com/16077030/34859129-5a27509a-f78f-11e7-9a49-a2d36633220c.png)
 
![123](https://user-images.githubusercontent.com/16077030/34859109-41dd20aa-f78f-11e7-88eb-47d05741f2c5.png)

**Comment by Samuell1** [comment] 2018-01-12 08:27
Duplicate of #1182

**Closed** 2018-01-12 08:28 UTC
Labels: duplicated

**Comment by FDLFDL** [comment] 2018-01-12 08:35
thank you ,my see
