### ISSUE TITLE
rreturn not defined error

### ISSUE THREAD

**Issue by NightravenJames** [vuematerial/vue-material#1730] opened 2018-05-14 11:04 UTC
I got the following error

![image](https://user-images.githubusercontent.com/18738423/39993735-887e87a6-577f-11e8-846d-eec168fb5335.png)

It also exists in  the documented example provided in this link ... please help I could really user this API
[https://codesandbox.io/s/pwoorq7l4m?module=App.vue](https://codesandbox.io/s/pwoorq7l4m?module=App.vue)

**Comment by Samuell1** [comment] 2018-05-14 11:12
Duplicate of #1727

**Closed by Samuell1** 2018-05-14 11:12 UTC
