### ISSUE TITLE
[MdTable] md-table-empty-state appears even when the table is populated.

### ISSUE THREAD

**Issue by mattgrande** [vuematerial/vue-material#1614] opened 2018-03-20 13:01 UTC
### Steps to reproduce

1. Currently using vue 2.5.13, vue-material 1.0.0-beta-8, vuex 3.0.1
2. Create an `md-table` populated via vuex (code below) that includes an `md-table-empty-state`
3. Scroll to the bottom of the page
4. Despite there being data, the `md-table-empty-state` appears

### Which browser?

Currently testing on OSX, Chrome 65.

### What is expected?

The `md-table-empty-state` should only appear when there's no data.

### What is actually happening?

The `md-table-empty-state` is always happening

### Reproduction Link

https://codesandbox.io/s/y2wyporwr9

**Edit:** Reproduction repo here: https://github.com/mattgrande/md-empty-state-reproduce

**Comment by Samuell1** [comment] 2018-03-20 17:49
Hey, we found out its not issue in vue-material but in codesandbox compiler. We are solving it with codesandbox devs.

For example here on Codepen it works: https://codepen.io/anon/pen/OvpyZL

**Comment by Samuell1** [comment] 2018-03-20 19:54
@mattgrande depends on what version you using of vue, vue-template-compiler and vue-loader

**Comment by mattgrande** [comment] 2018-03-20 19:55
My current dependencies:

```
"axios": "0.18.0",
"register-service-worker": "^1.0.0",
"vue": "^2.5.13",
"vue-class-component": "^6.0.0",
"vue-material": "1.0.0-beta-8",
"vue-property-decorator": "^6.0.0",
"vue-router": "^3.0.1",
"vuex": "^3.0.1"
```

Do you see anything amiss there?

**Comment by Samuell1** [comment] 2018-03-20 20:08
Can you check `vue-template-compiler` and `vue-loader`?

**Comment by mattgrande** [comment] 2018-03-20 20:42
`vue-template-compiler` is at 2.5.15 and `vue-loader` is 14.2.1.

**Comment by Samuell1** [comment] 2018-03-20 21:34
We using vue-loader `13.7.0`. maybe thats the issue

**Comment by Samuell1** [comment] 2018-03-21 07:18
@mattgrande What template you using from vue-cli?

**Comment by mattgrande** [comment] 2018-03-21 12:39
vue-loader for me is coming in as a dependency of vue/cli-service, which I have at `3.0.0-beta.6` (the latest).

My template uses the following: `vue-router, vuex, sass, babel, typescript, pwa, unit-mocha, e2e-nightwatch`.

I'm going to try upgrading all of my dependencies, see if that helps.

(Oh, and thank you for your help thus far!)

**Comment by Samuell1** [comment] 2018-03-21 12:56
Or it can depends on node version?

**Comment by mattgrande** [comment] 2018-03-21 12:57
I'm on node 8.10.0 currently.

**Comment by mattgrande** [comment] 2018-03-21 13:05
Same issue with node 9.8.0 as well :/

I'll try and create a repo that duplicates this afternoon so you can see what I see.

**Comment by Samuell1** [comment] 2018-03-21 14:10
@mattgrande do you tried to remove package-lock and node_modules?

**Comment by mattgrande** [comment] 2018-03-21 14:39
I have, yes. (Well, `yarn.lock`, but same idea)

**Comment by CompuIves** [comment] 2018-03-21 15:42
Hey @mattgrande, could you maybe open up a temporary github repo with the reproducible example so we can test it locally with the same dependencies? This is a really interesting case.

**Comment by Samuell1** [comment] 2018-03-22 08:36
Until we resolve it you can use this simple hack `v-if="roles.length === 0"` on `md-table-empty-state`.

**Comment by VdustR** [comment] 2018-03-22 12:28
I still can't not reproduce it with new webpack environment with module version from yours.

**Comment by mattgrande** [comment] 2018-03-22 12:36
Reproduce case: https://github.com/mattgrande/md-empty-state-reproduce

Let me know what I'm doing wrong :)

**Comment by Samuell1** [comment] 2018-03-22 13:10
Looks like mostly something is changed or fixed in new Vue version.

**Comment by mattgrande** [comment] 2018-03-22 13:37
I just noticed on my first page, I said I was using `2.5.13`, however in package.json it was `^2.5.13` and had actually resolved to `2.5.15`; The reproduce repo is pinned to `2.5.16`.

Coming from Angular, I can't believe how often Vue updates versions...

**Comment by Samuell1** [comment] 2018-03-31 15:53
@mattgrande your installed version depends on `package-lock` file

**Comment by Samuell1** [comment] 2018-04-09 16:47
@mattgrande As you can see i found a issue, do you think you can try it? If works for you, i merge it to dev.

To test it you can update your local dist file at line https://github.com/vuematerial/vue-material/blob/dev/dist/vue-material.js#L27023 or use my PR and compile new version.

**From:**
`_vm.value ? _vm._t("default") : _vm._e()`
**To:**
`!_vm.hasValue ? _vm._t("default") : _vm._e()`

**Comment by mattgrande** [comment] 2018-04-10 17:56
Hey @Samuell1 I'm happy to report this works! My only (very minor) concern is that the `thead` still appears; Is that intentional?

**Comment by Samuell1** [comment] 2018-04-10 18:34
@mattgrande i think table head is intentional to show. 

Thanks for helping me to test it!

**Closed** 2018-04-10 18:37 UTC
Labels: bug
