### ISSUE TITLE
mdSelect Doesn't show in dialogs

### ISSUE THREAD

**Issue by pizzapanther** [vuematerial/vue-material#1331] opened 2017-12-22 13:05 UTC
### Steps to reproduce

Put an md-select in a dialog

### Which browser?
```
"vue": "^2.5.9"
"vue-material": "^1.0.0-beta-7",
Chrome OS 62
```

### What is expected?

See the select options

### What is actually happening?

You don't see anything

### Reproduction Link

Screenshot: http://nimb.ws/TICE1V

Added a `z-index` and it fixes it: 
http://nimb.ws/3dLIuQ

**Comment by Samuell1** [comment] 2017-12-22 13:18
Duplicate of https://github.com/vuematerial/vue-material/issues/1149

**Closed by Samuell1** 2017-12-22 13:18 UTC
