### ISSUE TITLE
The sample code for Demo doesn't match with Multiple Options in List Component page.

### ISSUE THREAD

**Issue by joshua1988** [vuematerial/vue-material#723] opened 2017-05-04 11:12 UTC
As I was looking at the List Component on the official documentation, it appeared to me that the sample code on Control panel didn't really match with the demo at the very last part.

Guess it should be adding more contents to explain how the [Multiple Options](https://vuematerial.github.io/#/components/list) works.

Thanks for this awesome library by the way!

**Comment by Morgul** [comment] 2017-05-08 19:04
This looks like a duplicate of #486.

**Closed** 2017-05-14 16:10 UTC
Labels: duplicated
