### ISSUE TITLE
[MdSelect] keystroke scroll to value

### ISSUE THREAD

**Issue by VincentMRA** [vuematerial/vue-material#1820] opened 2018-06-19 00:56 UTC
[MD-Select]

Hi!

I am using the MD-Select with an alphabetised array of the countries of the world, which makes it a rather big select.
is there any way to jump to the letter upon a keypress?

I know the autocomplete would be an alternative solution but i'd rather stick with the select if there is any way to make this work.

Thank you!!

**Comment by Samuell1** [comment] 2018-06-19 07:22
Duplicate of #260

**Closed by Samuell1** 2018-06-19 07:22 UTC
