### ISSUE TITLE
[mdAutocomplete] Issue with custom templates and selecting an item

### ISSUE THREAD

**Issue by iamaaron** [vuematerial/vue-material#1395] opened 2018-01-12 03:18 UTC
### Steps to reproduce

Use custom template method according to mdAutocomplete documentation, with an array of objects. My example, https://vuematerial.io/components/autocomplete:

```
<template>
  <div>
    <md-autocomplete v-model="value" :md-options="colors">
      <label>Color</label>

      <template slot="md-autocomplete-item" slot-scope="{ item, term }">
        <span class="color" :style="`background-color: ${item.color}`"></span>
        <md-highlight-text :md-term="term">{{ item.name }}</md-highlight-text>
      </template>

      <template slot="md-autocomplete-empty" slot-scope="{ term }">
        No colors matching "{{ term }}" were found. <a @click="noop()">Create a new</a> one!
      </template>

      <div class="md-helper-text" v-if="value">
        <strong>Selected Color:</strong>
        <span class="color" :style="`background-color: ${value.color}`"></span>
      </div>
    </md-autocomplete>
  </div>
</template>
```

Note the error in the console that is fired when selecting an item:

![md-autocomplete](https://user-images.githubusercontent.com/2694192/34859219-86cd3c2e-f71a-11e7-82c3-c5ec424b8f08.png)

### Which browser?

- Google Chrome Version 62.0.3202.62 (Official Build) (64-bit)
- Vue Material 1.0.0-beta-7
- Vue 2.5.4

### What is expected?

I expect not to see an error when selecting an item, doesn't appear to be setting the selected item value in data either.

### What is actually happening?

The placeholder text is not changing, and the data object is not updated to reflect the selection. Also an error is output in the console.

### Reproduction Link

Steps provided above.

**Comment by Samuell1** [comment] 2018-01-12 08:24
Duplicate of #1243

**Closed** 2018-01-12 08:28 UTC
Labels: duplicated
