### ISSUE TITLE
Layout fixed to full height of browser window

### ISSUE THREAD

**Issue by cquick** [vuematerial/vue-material#1403] opened 2018-01-15 15:31 UTC
I'm looking to potentially use this framework with an upcoming project, but I need a way to force the layout to fill the full screen. Perhaps I'm missing a directive in the md-app component, but I have tried creating custom styles as well and cannot seem to get the layout to fill a browser window fully. 

### Steps to reproduce

View the codepen for the default app layout (https://codepen.io/pen?&editors=111).
Attempt to resize the md-app container using height: 100%. 

### Which browser?
I've only tested this in Chrome.

### What is expected?
I was expecting the layout to fall into a full screen with the "app" div filling the screen. 

### What is actually happening?
The content only sizes to the maximum size of the contained content.

**Comment by Samuell1** [comment] 2018-01-15 16:41
Duplicate of #1222

**Closed by Samuell1** 2018-01-15 16:41 UTC
