### ISSUE TITLE
 [mdSnackbar] disappearing instantly

### ISSUE THREAD

**Issue by Birssan** [vuematerial/vue-material#591] opened 2017-03-07 08:01 UTC
Hi there,

I've noticed an issue which happens with the snackbar, it doesn't occur everytime, and I can't really explain the procedure to reproduce the problem as its very random.

Sometime I open the snackbar (with the open method), the snackbar shows up and disappears almost instantly.
If I check the Chrome dev tools, I can see the snackbar div is created and the body element has the new classes added by the event like this

![created](https://cloud.githubusercontent.com/assets/5689193/23647270/51785990-0315-11e7-8cbe-1ffa953be400.png)

But not even after a second the snackbar element is removed leaving only the body classes related to the snackbar, like this
(The 'close' event is not triggered before the end of the duration though)

![destroyed](https://cloud.githubusercontent.com/assets/5689193/23647290/6a77bd50-0315-11e7-97e4-cdb848634915.png)

Then the snackbar classes added to the body are removed after the duration time set to the snackbar has passed (and the 'close' event is triggered)

I've tried to figure out why this happens, and more importantly, when it happens, but so far, it's so random that I can't really figure it out. 
In my project I use vuex to handle the snackbar state globally in the store, at first I thought I was maybe doing something wrong.

I cloned this project, ran it locally and the issue occurs as well in the Snackbar example.

I just noticed that it occurs after a while if you close manually the Snackbar (with the Retry button in the example), open it again, close it again and so on

**Comment by Samuell1** [comment] 2017-03-07 09:02
+1

**Comment by nirkki** [comment] 2017-03-13 14:05
Just noticed the same. Snackbar is opened but immediately closed. Close event comes after 4s as it is supposed to do.

**Comment by fergardi** [comment] 2017-03-21 08:18
I also noticed this, but could not reproduce it myself. It appears to happen when the app is open for long periods of time (>5m), then suddenly the snackbar shows and dissapears in 1s, ignoring the md-duration attribute.

**Comment by Linzdigr** [comment] 2017-09-09 17:13
It seems https://github.com/vuematerial/vue-material/blob/b802afd4346feb0093fc0a09513e9df9b233b29c/src/components/mdSnackbar/mdSnackbar.vue#L97 is called when the snackbar ends its open animation, so I guess the eventListener on _transitionend_ (initiated at https://github.com/vuematerial/vue-material/blob/b802afd4346feb0093fc0a09513e9df9b233b29c/src/components/mdSnackbar/mdSnackbar.vue#L106) is not always cleared properly.
This happen once the close() method is called at least once (in other words not on the first snackbar opened).

**Comment by Samuell1** [comment] 2017-11-23 20:19
Closing this issue as our focus is on the new 1.0.0 version.

**Closed by Samuell1** 2017-11-23 20:19 UTC
Labels: bug
