### ISSUE TITLE
[MdAutocomplete] Programmatic interaction with autocomplete v-model throws error and opens panel

### ISSUE THREAD

**Issue by atinybeardedman** [vuematerial/vue-material#1825] opened 2018-06-22 17:33 UTC
### Steps to reproduce
Register a v-model with md-autocomplete and then set the value of that v-model variable to null.
### Which browser?

Chrome, Vue 2.5.16, vue-material-1.0.0-beta-10.2

### What is expected?

Autocomplete should gracefully handle null values to v-model, not throw an error.

### What is actually happening?

Error in event handler for "input": "TypeError: Cannot read property 'constructor' of null"

Also autocomplete is given focus and the panel of options is opened whenever the value is set programmatically as well. I tried setting the value to a null string and this avoids the error but the panel still opens and the input is given focus.

### Reproduction Link

https://codesandbox.io/s/50q7q2273p?module=%2FApp.vue

**Comment by Samuell1** [comment] 2018-06-28 06:53
Duplicate of #1243

**Closed by Samuell1** 2018-06-28 06:53 UTC
