### ISSUE TITLE
[MdSnackbar] Uncaught TypeError: Cannot read property '_vnode' of undefined

### ISSUE THREAD

**Issue by dakshshah96** [vuematerial/vue-material#1920] opened 2018-09-01 14:56 UTC
### Steps to reproduce

```
<template>
  <md-content>
    <form @submit="submitForm">...</form>
    <md-snackbar md-position="center" :md-active.sync="loginMessage.status">
      <span>{{loginMessage.message}}</span>
    </md-snackbar>
  </md-content>
</template>
<script>
export default {
  name: 'login',
  data: () => ({
    loginMessage: {
      active: false,
      message: ''
    }
  }),
  methods: {
    submitForm () {
      this.loginMessage = { status: true, message: 'Please wait while we log you in...' }
      this.$store.dispatch('login', {
      	phoneNumber: this.loginForm.phoneNumber,
        password: this.loginForm.password
      })
        .then((res) => {
          console.log(res)
          this.loginMessage = { status: true, message: 'Login successful!' }
          this.$router.replace('/dashboard')
        })
		.catch((err) => {
          console.error(err) 
        })
    }
  }
}
</script>
```

The 'Please wait while we log you in...' snackbar is displayed without any errors. Once login is successful, it is replaced with the 'Login successful!' text and user is redirected to the `/dashboard` page.

After getting redirected to `/dashboard`, the following error is printed in my console after 2-3 seconds:

```
Uncaught TypeError: Cannot read property '_vnode' of undefined
    at eval (vue-material.js?43f9:27001)
(anonymous) @ vue-material.js?43f9:27001
setTimeout (async)
(anonymous) @ vue-material.js?43f9:26998
createPromise @ vue-material.js?43f9:26989
createSnackbar @ vue-material.js?43f9:27027
mdActive @ vue-material.js?43f9:10507
run @ vue.runtime.esm.js?2b0e:3229
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:2977
(anonymous) @ vue.runtime.esm.js?2b0e:1833
flushCallbacks @ vue.runtime.esm.js?2b0e:1754
```

### Which browser?

Vue: v2.5.17
Vue Material: v1.0.0-beta-10.2
OS: macOS Mojave Public Beta 7
Browser: Google Chrome 68.0.3440.106 (Official Build) (64-bit)

### What is expected?

No errors/warnings in console.

### What is actually happening?

An errors in console as described above.

**Comment by VdustR** [comment] 2018-09-04 21:12
related to #1791

**Comment by VdustR** [comment] 2018-09-04 21:13
@dakshshah96 did you try it with `dev` branch?

**Comment by darkoromanov** [comment] 2018-09-26 16:53
Sorry for the dummy question but how do I select the dev branch from npm? I have the same issue using 1.0.0-beta-10.2

**Comment by sokudo** [comment] 2018-10-21 09:46
In md-snackbar implementation, a call to`createPromise()` is made with an incorrect number and order of arguments.
The function `createPromise(duration, persistent, context)` is called  as`createPromise(duration, context)`.
So `context` within `createPromise()` is undefined and that causes an exception in ` context._vnode.componentInstance.initDestroy(true);` 

A  snippet:
```var createSnackbar = exports.createSnackbar = function createSnackbar(duration, context) {
  if (currentSnackbar) {
    return destroySnackbar().then(function () {
      return createPromise(duration, context);
    });
  }

  return createPromise(duration, context);
};


function createPromise(duration, persistent, context) {
```

**Comment by syonip** [comment] 2018-11-30 06:52
This fix already exists in the dev branch.
To save you some time, this is what you need to run:

npm i "vue-material@vuematerial/vue-material#dev"

**Comment by Samuell1** [comment] 2018-12-25 13:16
Duplicate of #1791

**Closed by Samuell1** 2018-12-25 13:16 UTC
Labels: duplicated
