### ISSUE TITLE
 [SCSS] md-flex-small bug

### ISSUE THREAD

**Issue by primadi** [vuematerial/vue-material#728] opened 2017-05-06 15:20 UTC
### Steps to reproduce
open layout demo page : https://vuematerial.github.io/#/ui-elements/layout

### Which browser?
vue-material 0.7.1, Windows 10, Chrome Browser

### What is expected?
On Responsive Demo, it must show different layout from md-flex-small and md-flex-medium.

### What is actually happening?
there is no different layout between md-flex-small and md-flex-medium.

**Comment by herlon214** [comment] 2017-05-25 17:51
There's no fix yet? The responsiveness seems to be not working =/

**Comment by pablohpsilva** [comment] 2017-05-30 16:26
Thanks for reporting this issue @primadi ! :D 
We'll look into it asap

---
What do you mean @herlon214 ?

**Comment by bitencode** [comment] 2017-06-13 00:50
I was going to open an issue on this, but found this one, so I'll add to it instead.   
It looks to me like the class definitions for @media break-points are in the generated CSS file in the wrong order.
For example, in my markup I have the following (using Pug):
 ```
md-layout(
    md-flex-small="100"
    md-flex-medium="50"
    md-flex="33"
)
```
The resulting markup looks like this:
```
<div class="md-layout md-flex-33 md-flex-small-100 md-flex-medium-50>...</div>
```
That all looks fine, however, when the browser width is "small" the definition of `md-flex-medium-*` take precedence over the `md-flex-small-*` definitions.  A screen capture shows the problem:
<img width="440" alt="designer" src="https://user-images.githubusercontent.com/787250/27061158-aba883ea-4f96-11e7-9a0b-8e29d5cd4da0.png">
 
After some testing, it appears to me that this is a problem with all the `mf-flex` break-points.  Only the "largest" break-point size take effect in addition to the non-size specified `md-flex`.  So, if you have large, medium, small, and xsmall all specified, only the large will take affect.
Pretty sure they will have to be defined from xsmall through xlarge in ascending order.

**Comment by bitencode** [comment] 2017-06-13 01:26
I did some more testing, and of course, I'm partially wrong in the last comment.  `small` is the only one that doesn't work right - it *always* is in the CSS at the end so never takes affect.  The others all work properly, so if you user `large`, `medium`, `xsmall` it will have all the break-points set properly.

**Comment by juanfabrega** [comment] 2017-06-15 09:37
Hi -- I'm experiencing the same issue. Currently md-flex-small does not take effect on any component. The rest of the breakpoints seem to work great. If anybody has any workarounds that would be fantastic!

**Comment by primadi** [comment] 2017-06-15 17:07
@juanfabrega just for workaround issue, you can use css :

```
$small-size:600px;

.small-visible {
  @media (min-width: $small-size+1) {
    display: none;
  }
}

.small-hide {
  @media (max-width: $small-size) {
    display: none;
  }
}
```

**Comment by juanfabrega** [comment] 2017-06-16 17:46
Hi @primadi, thanks so much for your help here! 

I'm not sure I fully understood your suggestion. Any chance you could walk me through what these blocks are accomplishing? Also, are you suggesting I place these within the scoped style of my component? Thanks again!

**Comment by capttrousers** [comment] 2017-06-17 23:35
+1

also this seems to be a duplicate of #546

**Comment by jan-swiecki** [comment] 2017-09-11 11:21
Same problem.

```<md-layout md-gutter>
  <md-layout md-flex-xsmall="50">Test</md-layout>
  <md-layout md-flex-xsmall="25">Test</md-layout>
  <md-layout md-flex-xsmall="25">Test</md-layout>
</md-layout>```

This shows as three same width columns (doesn't work for small and xsmall).

**Comment by strujillo6** [comment] 2017-09-17 19:38
To solve the problem, you should look in the Css section of breakpoints, and place at each point a limitation, for example in the small one, you must put @media (min-width: 601px) and (max-width: 944px) , for the medium @media (min-width: 945px) and (max-width: 1264px) and large @media (min-width: 1265px) and (max-width: 1903px).
Sorry for my English

**Comment by murilodag** [comment] 2017-10-01 01:06
Hello @pablohpsilva, could you enroll to the Hacktoberfest? I think it would help to encourage people to fix these issues.

**Comment by vitorcominato** [comment] 2017-10-06 11:53
Same problem here

**Comment by ORoy** [comment] 2017-10-13 04:27
+1

**Comment by JoryOne** [comment] 2017-10-17 12:12
Version 0.7.5  still has the same problem, md-flex-xsmall & md-flex-medium works fine, but md-flex-small not

**Comment by Samuell1** [comment] 2017-11-23 20:36
Closing this issue as our focus is on the new 1.0.0 version.

**Closed by Samuell1** 2017-11-23 20:36 UTC
Labels: bug
