### ISSUE TITLE
[mdAutocomplete]  Error in nextTick: "Error: You should use a `fetch` function prop"

### ISSUE THREAD

**Issue by alexMugen** [vuematerial/vue-material#1002] opened 2017-08-25 13:52 UTC
Hello, 

i want to use md autocomplete, with list prop and filteredList but i have an error 
 

> Error in nextTick: "Error: You should use a `fetch` function prop"

my code below : 
 `<md-autocomplete :min-chars="3" v-model="searchAgenciesQuery" :list="agencies" :filter-list="filteredAgencies" ">`

agencies is the result of my promise 
```javascript
Services.getAgencies({size: 1000, page: 0}).then(resp => {
        this.agencies = resp
      })
```

filteredAgencies is my filter method : 
```javascript
filteredAgencies () {
        let query = this.searchAgenciesQuery
        if (query) {
          return this.agencies.filter(agency => {
            let filterByName = agency.name ? agency.name.toLowerCase().includes(query.toLowCase()) : ''
            let filterById = agency.id !== null ? agency.id.includes(query) : ''
            return filterByName || filterById
          })
        }
      }
```

I don't understand the difference between list prop and fetch prop. I don't use fetch cuz i have to store locally my agencies, so my promise is not for the fetch that it should return but it implement on the created, so i dont want to use fetch way
```javascript
 created () {
      Services.getAgencies({size: 1000, page: 0}).then(resp => {
        this.agencies = resp
      })
    },
```

Thanks a lot for your help

**Comment by alexMugen** [comment] 2017-08-25 14:36
i tried with fetch prop and i have the same problem.

my code : 

``
<md-autocomplete :min-chars="3" v-model="searchAgenciesQuery" :fetch="filteredAgencies"></md-autocomplete>
``

```javascript
filteredAgencies () {
        Services.getAgencies({size: 1000, page: 0}).then(resp => {
          return resp
        }).then(resp => {
          let query = this.searchAgenciesQuery
          if (query.length > 1) {
            return resp.filter(agency => {
              let filterByName = agency.name ? agency.name.toLowerCase().includes(query.toLowCase()) : ''
              let filterById = agency.id !== null ? agency.id.includes(query) : ''
              return filterByName || filterById
            })
          } else {
            return resp
          }
        })
      }
```
Moreover i have this errors when i click on the field

> Cannot read property 'focus' of undefined

> Cannot read property 'value' of undefined

**Comment by VdustR** [comment] 2017-08-25 18:34
I wrote an [example](https://codepen.io/VdustR/pen/prOJzL) for you.

`filter-list`: Yous should pass a function.
```javascript
{
  methods:{
    filterList: (list, inputString) => {
      // do some thing
      return result
    }
  }
}
```

`fetch`: You should return a promise in your fetch method or declare it as an async function.
```javascript
{
  methods:{
    async fetch: ({q}) => {
      let inputString = q
      let result = await getResult(inputString)
      return result
    }
  }
}
```

Use `list` and `filter` props if you don't need to do an async method (like ajax) to get the result,
or use `fetch` props if you have to.

It's more likely better to use `list` and `filter` props then `fetch` in your case that you only fetch the list once on component created.

**Comment by alexMugen** [comment] 2017-08-28 10:16
Hello,

Thank you for your helping ! 
I understand now difference between differents props list and fetch but i cannot use it  but I'm sorry i can't make it works, i have this error

> You should use a `filterList` function prop with the `list` prop

```javascript
methods: {
      filteredAgencies: (agencies = this.agencies, query = this.searchAgenciesQuery) => {
        return agencies.filter(agency => {
          let filterByName = agency.name ? agency.name.toLowerCase().includes(query.toLowerCase()) : ''
          let filterByRegion = agency.address.region ? agency.address.region.toLowerCase().includes(query.toLowerCase()) : ''
          let filterById = agency.id !== null ? agency.id.includes(query) : ''
          return filterByName || filterById || filterByRegion
        })
      }
    }
```

I pass anonymous method to filteredAgencies and my html is the same as before: 
`                <md-autocomplete :min-chars="3" v-model="searchAgenciesQuery" :list="agencies" :filter-list="filteredAgencies"></md-autocomplete>
`

**Comment by VdustR** [comment] 2017-08-28 11:32
What error did you got?

Could you please reproduce it in codepen?

**Comment by alexMugen** [comment] 2017-08-28 12:17
here my copend => https://codepen.io/Alex_Mugen/pen/wqYJew?editors=1011

thank you !

**Comment by alexMugen** [comment] 2017-08-28 12:17
my error : 

> [Vue warn]: Error in nextTick: 'Error: You should use a `filterList` function prop with the `list` prop'

**Comment by alexMugen** [comment] 2017-08-28 12:40
oups , i changed version of dependencies now it'swork on codepend , maybe i will try the same on my project

**Comment by alexMugen** [comment] 2017-08-28 13:10
i think i have an idea , in my console i have first the error concerning filter list props, then , i have my response (200 status) of my promise getAgencies setted in my computed of my vue

**Comment by alexMugen** [comment] 2017-08-28 13:19
i put my filteredAgencies  called by filter-list prop in my computed instead of my methods beause computed is execute before the mounted , i have another error 

> Vue warn]: Avoid using non-primitive value as key, use string/number value instead.

**Comment by alexMugen** [comment] 2017-08-28 13:26
i really don't understand , i refresh page now i have : 

>  Error in nextTick: "Error: You should use a `fetch` function prop"

**Comment by VdustR** [comment] 2017-08-28 13:43
```
[Vue warn]: Avoid using non-primitive value as key, use string/number value instead.
```

Because the list should be a list of distinct strings.

e.g.
```javascript
{
  data () {
    return {
      list: ['str1', 'str2', 'str3']
    }
  }
}
```

You put objects in list array.

Thus, the key of the menu is the agency objects. That cause this warning.

It's better to computed a distinct string array list from the original list to pass as `:list`

**Comment by alexMugen** [comment] 2017-08-28 13:47
thank you for your explanation for 

> [Vue warn]: Avoid using non-primitive value as key, use string/number value instead.

I tried differents solutions but i cannot find the right , i have again 

> vue.esm.js?65d7:566 Error: You should use a `filterList` function prop with the `list` prop

while on the copen it works

**Comment by VdustR** [comment] 2017-08-28 14:04
I cannot help you if you don't reproduce it.

**Comment by VdustR** [comment] 2017-08-28 14:59
I misunderstood about the warning:
> [Vue warn]: Avoid using non-primitive value as key, use string/number value instead.

I check the [code b802afd mdAutocomplete line 26](https://github.com/vuematerial/vue-material/blob/b802afd4346feb0093fc0a09513e9df9b233b29c/src/components/mdInputContainer/mdAutocomplete.vue#L26)

That list should be an object list so it's seem like the warning always happen.

You could decide what property key to show or select by the `:print-attribute`, which default is `name`.

**Comment by alexMugen** [comment] 2017-08-28 15:09
ok thank you for the precision :1st_place_medal:

**Comment by alexMugen** [comment] 2017-08-28 15:39
I cannot understand the mistake..
https://codepen.io/Alex_Mugen/pen/wqYJew?editors=1011 i copy paste the same from my webpack project ( expect method get that calling service but even if i mockup agencies with array static it doesn't work )

i have a template : 
`<md-autocomplete :min-chars="3" v-model="searchAgenciesQuery" :list="agencies" :filter-list="filteredAgencies"></md-autocomplete>`

i have a created that get agencies : 
```javascript
Services.getAgencies({size: 1000, page: 0}).then(resp => {
        this.agencies = resp
      })
```

I have a methods that contains filteredAgencies : 

```javascript
filteredAgencies () {
        console.log('filteredAgencies')
        return this.agencies.filter(agency => {
          let filterByName = agency.name ? agency.name.toLowerCase().includes(this.searchAgenciesQuery.toLowerCase()) : ''
          let filterByRegion = agency.address.region ? agency.address.region.toLowerCase().includes(this.searchAgenciesQuery.toLowerCase()) : ''
          let filterById = agency.id !== null ? agency.id.includes(this.searchAgenciesQuery) : ''
          return this.searchAgenciesQuery.length > 1 ? filterByName || filterById || filterByRegion : this.agencies
        })
      },
```

:hankey:

**Comment by VdustR** [comment] 2017-08-28 16:18
Did you upgrade the modules to latest version?

**Comment by alexMugen** [comment] 2017-08-29 07:55
i think is already the latest version because in my package json i have 
`"vue": "^2.3.3",
    "vue-material": "^0.7.1"`

It means that it take the latest right  ?

**Comment by VdustR** [comment] 2017-08-29 08:06
Execute this command in your project directory to check modules installed
```
npm ls --depth=0
```

**Comment by alexMugen** [comment] 2017-08-29 08:12
Thank you !
It looks like is ok 
```javascript
vue@2.4.2
├── vue-loader@12.2.2
├── vue-material@0.7.4
├── vue-router@2.7.0
├── vue-style-loader@3.0.1
├── vue-template-compiler@2.4.2
├── webpack@2.7.0
├── webpack-bundle-analyzer@2.9.0
├── webpack-dev-middleware@1.12.0
├── webpack-hot-middleware@2.18.2
└── webpack-merge@4.1.0
```

**Comment by alexMugen** [comment] 2017-08-29 08:27
i compare two code again and it's exaclty the same, i set my agencies to a local array as code pen because it s the only difference but it doesn't work :imp:

**Comment by alexMugen** [comment] 2017-08-29 08:39
Sorry i missed something , 

i tested to set a local array like this : 
```javascript
Services.getAgencies({size: 1000, page: 0}).then(resp => {
        this.agencies = [{name:'toto', region: 'test', id: '123'},
                     {name:'tata', region: 'aze', id: '456'},
                     {name:'titi', region: 'taiwan', id: '789'}]
      })
```
instead  of set agencies without promise 
```javascript
this.agencies = [{name:'toto', region: 'test', id: '123'},
                     {name:'tata', region: 'aze', id: '456'},
                     {name:'titi', region: 'taiwan', id: '789'}]
```

now i have the error we talked before 

> [Vue warn]: Avoid using non-primitive value as key, use string/number value instead.

**Comment by VdustR** [comment] 2017-08-29 08:46
It's not a fatal error. I think you could ignore it temporarily.

I have no idea whether this change with the key of the menu item is a good idea or not:
```html
<md-menu-item v-if="items.length"
  v-for="item in items"
  :key="item[printAttribute]"
  @keyup.enter="hit(item)"
  @click="hit(item)">
  {{ item[printAttribute] }}
</md-menu-item>
```

**Comment by alexMugen** [comment] 2017-08-29 09:09
ok ,  i will use  md-autocomplete if it'ss not a fatal error !

i want to say you thank you a lot :1st_place_medal:

**Comment by SergioReis97** [comment] 2017-09-15 15:01
Kept getting the error 

> You should use a filterList function prop with the list prop

Tinkered around and got it to work like this
`<md-autocomplete name="autoComplete" id="autoComplete" :filterList="someFunction" :min-chars="0" :list="[{name:''}]"  v-model="myModel"></md-autocomplete>`

. 
.
.
```
methods:{
    someFunction() {
      // TODO actual filtering
      return this.myList;
    },
    getFunctionThatIsCalledOnCreate(){
          this.$http.get(url, {}).then((response) => {
        var result = response.data;
        if (this.myList != result.myListFromServer) {
          var outputList = [];
          for (var k in result.advogados) {
           // Pretty sure there are better and easier ways of doing this (converting string array to object array with a prop)
            var line = result.myListFromServer[k];
            outputList.push({ name: line });            
          }
          if (outputList != null && outputList != [])
            this.myList = outputList;
        }
      })
   }
}
```
Using name since its default but can be changed in 'print-attribute' prop

**Comment by Samuell1** [comment] 2017-11-23 19:53
Closing this issue as our focus is on the new 1.0.0 version.

**Closed by Samuell1** 2017-11-23 19:53 UTC

**Comment by fpinzn** [comment] 2017-12-15 16:27
In case anyone is using the 0.8.1 version and gets this error.  It happens when the initial state of the list you're pointing to is empty. Simply initialize the list with fake data. Something like:

`list= [{name: 'loading', id: -1}]`
