### ISSUE TITLE
Form elements do not have associated labels

### ISSUE THREAD

**Issue by dm-heinze** [vuematerial/vue-material#1991] opened 2019-01-11 10:50 UTC
### Steps to reproduce

Use MdSelect component, perform google lighthouse audit and check accessability audit results

### Which browser?

Google Chrome 

### What is expected?

Audit should pass

### What is actually happening?

Audit fails with error message:
Form elements do not have associated labels.
Labels ensure that form controls are announced properly by assistive technologies, like screen readers.

Failing Elements:
`<input type="text" id="md-input-kn1ij78yh" readonly="readonly" class="md-input md-input md-select-value">`
`<input readonly="readonly" tabindex="-1" class="md-input-fake">`
`<select readonly="readonly" tabindex="-1"></select>`

Would be great, if you could add labels for those input and select fields so the inputs can be read correctly by screenreaders. 
Please add aria-hidden="true" for all elements wich are not displayed anyway.

**Comment by Samuell1** [comment] 2019-01-29 09:44
Duplicate of #83

**Closed by Samuell1** 2019-01-29 09:44 UTC
