### ISSUE TITLE
to export vue components directly  

### ISSUE THREAD

**Issue by xiongbinsh** [vuematerial/vue-material#1624] opened 2018-03-24 08:17 UTC
in current version, all components are exported as plugins of Vue, that are installed by invoking method "Vue.use()" and all components are in global scope with a unchangeable name， and the DOM tag should use a certain <MdXXXX>   name.  But for legacy project,  it is a huge efforts to update the tag labels in every pages.  for example, there is a project with lot of `<tabs> and <list>` tag.

Is that possible to export the Vue component directly, so it could be used in local scope components and rename by user? :-)   something like: 
```
<template>
...
<tabs id='foo' class='bar'>
<list>
...
</list>
</tabs>
...
</template>
<script>
import MdTabs from "Mdtabs"
import MdList from "MdList"
exports default {
data: ... ,
components:{ list:MdList ,tabs: MdTabs }
}
</script>
```

**Comment by Samuell1** [comment] 2018-03-24 10:29
Duplicate of #1166

**Closed by Samuell1** 2018-03-24 10:29 UTC
