### ISSUE TITLE
[MdInput] doesn't put name attribute into inner input tag

### ISSUE THREAD

**Issue by goatandsheep** [vuematerial/vue-material#1655] opened 2018-04-02 00:49 UTC
### Steps to reproduce

```html
<form :action="endpoint" enctype="multipart/form-data" method="POST">
<md-input name="title" type="text" v-model="title"></md-input>
</form>
```

### Which browser?

Chrome 

### What is expected?

put the name attribute so i can send my form

### What is actually happening?

form is sending empty

**Comment by VdustR** [comment] 2018-04-02 01:30
Would you provide your code with Codepen or CodeSandbox?

**Comment by Samuell1** [comment] 2018-04-02 07:38
This was fixed in beta-8. Do you using beta-7?

**Comment by Y0hy0h** [comment] 2018-04-02 16:51
I could not reproduce this. See the [relevant CodeSandbox](https://codesandbox.io/s/rw38o95zyo).

Your code crashes on Chrome, since the `<md-field>` is missing. I therefore wrapped it around the `<md-input>`. Note however, that on Firefox the rendered `<input>` has the correct `name` attribute both with and without the `<md-field>`.

It would thus appear that you are not using the newest version, as [Samuell1 pointed out](https://github.com/vuematerial/vue-material/issues/1655#issuecomment-377875984).

**Comment by goatandsheep** [comment] 2018-04-02 17:09
Yes, I'm using beta-7. I'll try upgrade and see if it is fixed

**Comment by Samuell1** [comment] 2018-04-03 12:12
@goatandsheep I closing for now if you get same error in new version, reply here and i reopend this issue.

**Closed** 2018-04-03 12:12 UTC
Labels: needs repro
