### ISSUE TITLE
md-autocomplete affected by custom css margin

### ISSUE THREAD

**Issue by michjk** [vuematerial/vue-material#1524] opened 2018-02-17 15:07 UTC
Steps to reproduce
Make template which wrap md-complete inside div that have custom style margin. Example:
```
<template>
  <div id="app">
    <md-autocomplete
      v-model="searchProductText"
      :md-options="productList">
      <label>Enter item name</label>
    </md-autocomplete>
  </div>
</template>

<script>
export default {
  data () {
    return {
      searchProductText: null,
      productList: [
        'book',
        'phone',
        'TV'
      ]
    }
  }
}
</script>

<style scoped>
#app {
 margin-top: 50px
}
</style>
```
Which version & browser?
Vue Material 1.0 beta 8, Chrome 64 Ubuntu

What is expected?
![image](https://user-images.githubusercontent.com/11803421/36342256-7f3a530a-1436-11e8-99a5-59696343affd.png)

What is actually happening?
The custom margin affect the recommendation dropdown
![image](https://user-images.githubusercontent.com/11803421/36342264-b81db978-1436-11e8-8837-99366e129937.png)

**Comment by Samuell1** [comment] 2018-02-17 15:19
Duplicate of #1206

**Closed by Samuell1** 2018-02-17 15:19 UTC
