### ISSUE TITLE
[MdAutoComplete] Buggy Demo Behavior

### ISSUE THREAD

**Issue by fizxmike** [vuematerial/vue-material#1383] opened 2018-01-09 18:17 UTC
### Steps to reproduce
Visit https://vuematerial.io/components/autocomplete/ under "Custom Template"->"With highlight text" click the "open on codepen" button.
1. click on empty text box, menu pops up, click an item...
1. type the letter "a" into the text box, menu pops up, click an item...
1. click on text box and type the letter "q" into the text box, menu pops up, select an item...
1. clear the selection
### Which browser?
Version 63.0.3239.108 (Official Build) (64-bit)
### What is expected?
1. the item gets selected and text matches selection
1. the item gets selected and text matches selection
1. the item gets selected and text matches selection
1. the item is dis-selected
### What is actually happening?
1. nothing, no item selected
1. item is partially selected but text in box does not match selected item (the selected color is displayed below the input box)
1. item is selected with text in box matching selected item. (finally!)
1. item is partially dis-selected? (the selected color remains below the input box)

### Reproduction Link
(cloned) from the documentation page: https://codepen.io/anon/pen/xpYjgE

**Comment by Samuell1** [comment] 2018-01-09 18:24
Duplicate of #1243

**Closed by Samuell1** 2018-01-09 18:24 UTC
