### ISSUE TITLE
 [mdTable] Setting md-total disables pagination on md-table-pagination

### ISSUE THREAD

**Issue by mehyaa** [vuematerial/vue-material#482] opened 2017-02-10 08:03 UTC
Hi,

On md-table-pagination setting md-total to a value changes the "Many" text to the value but it disables next and previous page actions.

Not setted:
![image](https://cloud.githubusercontent.com/assets/1491850/22818684/252784a8-ef77-11e6-923e-c729f9e6fe46.png)

Setted:
![image](https://cloud.githubusercontent.com/assets/1491850/22818695/2cbaa0b0-ef77-11e6-8e74-69da1d8a4cbf.png)

I'm updating datasource of rows on pagination events so there always are less or equals rows from pageSize.

**Comment by iwan-wijaya** [comment] 2017-02-11 11:03
I'm having the same problem, it's a bug https://github.com/marcosmoura/vue-material/issues/437

It looks like the `totalItems` property isn't updating 
https://github.com/marcosmoura/vue-material/blob/master/src/components/mdTable/mdTablePagination.vue#L51

For a temporal fix you can copy the component and add a computed property or a watcher.

**Comment by praneetloke** [comment] 2017-02-15 20:18
@mehyaa and @iwan-wijaya I hit the same problem too just now. It seems that, to get around this, you can set the total to the string 'Many' or a really high value. I prefer the former. The issue is that the criteria for the `disabled` attribute doesn't recalculate when its dependent properties are changed through paging.

See https://github.com/marcosmoura/vue-material/blob/master/src/components/mdTable/mdTablePagination.vue#L15

I am looking at spending some time fixing this. I'll update this thread if I do end up submitting a pull request.

**Comment by Flugund** [comment] 2017-08-28 06:54
Hey, this seems to still be a bug. Not working in v0.7.0. Is someone looking in to it?

**Comment by jamesvweston** [comment] 2017-08-30 14:44
I ran into this issue myself.
The problem is in the component md-table-pagination in the watcher for mdTotal.
The line "this.subTotal = sub > val ? val : sub" is assigning a value to subTotal, but that's a computed property so it fails. Commenting out that line fixes it:

mdTotal (val) {
        //  const sub = this.currentPage * this.currentSize

        //  this.subTotal = sub > val ? val : sub
        this.totalItems = isNaN(val) ? Number.MAX_SAFE_INTEGER : parseInt(val, 10)
      }

**Comment by Flugund** [comment] 2017-08-31 09:25
This issue seems to be fixed in the develop branch, would be really nice to release it!

**Comment by mburke05** [comment] 2017-09-25 18:11
Any updates on whether this has made it in the next scheduled release?

**Comment by jonalexander** [comment] 2017-11-09 21:49
hi - any updates on this bug? thanks.

**Comment by Samuell1** [comment] 2017-11-23 19:36
Closing this issue as our focus is on the new 1.0.0 version.

**Closed by Samuell1** 2017-11-23 19:36 UTC
Labels: bug
