### ISSUE TITLE
Horizontal Steppers not working when clicking button on the form

### ISSUE THREAD

**Issue by potapycha** [vuematerial/vue-material#1631] opened 2018-03-26 13:21 UTC
Hei,

https://vuematerial.io/components/steppers

When clicking on the button where using horizontal steppers, after any action on the browser not working...You can try pages "https://vuematerial.io/components/steppers" -> "Linear Steppers" -> click on the button "CONTINUE"

There is no such problem with vertical steppers.

Aleksandr

**Comment by Samuell1** [comment] 2018-03-26 16:42
Duplicate of #1555

**Closed by Samuell1** 2018-03-26 16:42 UTC
