### ISSUE TITLE
[MdAutocomplete] cannot select by clicking an item

### ISSUE THREAD

**Issue by simoneb** [vuematerial/vue-material#1909] opened 2018-08-22 09:03 UTC
### Steps to reproduce

- click on the autocomplete input to open the autocomplete list
- click on any item in the list (without typing anything)

### Which browser?

Chrome Version 69.0.3497.42 (Official Build) beta (64-bit) on Windows

### What is expected?

- the item is selected and displayed in the autocomplete input

### What is actually happening?

- nothing is selected

### Reproduction Link

https://codesandbox.io/s/q4nml15y6w

**Comment by daopapp** [comment] 2018-08-23 12:14
Hi man.
I founded this little trick for this bug on a closed issue.
Use the props v-on:md-opened="opened" calling a method opened, for example.
In this method:
opened () {
      this.name += ' '
      this.name = this.name.substring(0, this.name.length - 1)
    },
the this.name it's the v-model variable.
In my case, this works.

**Comment by simoneb** [comment] 2018-08-30 08:26
@jack-wi thanks, I'm not in a rush and I can wait until it's released. If you can take care of closing the issue when it's released I will test it out right away.

**Comment by Samuell1** [comment] 2018-08-31 07:08
Duplicate of #1740

**Closed by Samuell1** 2018-08-31 07:08 UTC
