### ISSUE TITLE
<md-list-item to="/"> not working <to="/">

### ISSUE THREAD

**Issue by bigidea-kz** [vuematerial/vue-material#2022] opened 2019-02-21 17:59 UTC
Thank you for your project.
I tried to use <md-list-item then = "/"> but it does not work, it gives an error "Error in render:" TypeError: Cannot read property 'options' of undefined "

my code

<md-list>
  <md-list-item to = "/">
    ......... 
 </ md-list-item>
</ md-list>

**Comment by AlvaroBrasilia** [comment] 2019-02-26 17:21
Duplicate of #1978

**Closed** 2019-02-28 19:09 UTC
