### ISSUE TITLE
<md-tabs> height doesn't change when content is added dynamically

### ISSUE THREAD

**Issue by arthursouviron** [vuematerial/vue-material#1595] opened 2018-03-12 11:56 UTC
### Steps to reproduce

Press the "add line" button, the size of the tab will not increase automatically, it is also not possible to scroll.

### Which browser?

Tested on Chrome V64.0

### What is expected?

The size of the tab content should increase automatically when adding content dynamically.

### What is actually happening?

The size of the `.md-tabs-content` doesn't seem to be recalculated unless the user switch tabs.
Setting `md-dynamic-height` to true doesn't fix the issue.

### Reproduction Link

https://codepen.io/arthur_souviron/pen/RMPmxo
or
https://codesandbox.io/s/mm4k19x6zj

**Comment by Samuell1** [comment] 2018-03-12 12:49
Duplicate of #1513

**Closed** 2018-03-12 12:52 UTC
