### ISSUE TITLE
Datepicker expects disabled dates via text input

### ISSUE THREAD

**Issue by KongJan** [vuematerial/vue-material#1945] opened 2018-10-08 09:12 UTC
### Steps to reproduce

configure a datepicker with disabled dates, e.g. no dates in the past:
```
<md-datepicker value="date" :md-disabled-dates="isDateDisabled">
  <label>no past dates</label>
</md-datepicker>
```
```
isDateDisabled: function(date) {
  // compare if today is greater then the datepickers date
  return new Date() > date
}
```
After this you can still manually type in an invalid date via keyboard input and it gets set in the value of the datepicker component.

### Which browser?

Chrome, version 69.0.3497.100

### What is expected?

Value should not be set

**Comment by zapping** [comment] 2018-10-12 14:59
#1759

**Comment by KongJan** [comment] 2018-10-15 11:07
This improvement would be nice to avoid my bug, but I think the manual input of disabled dates should still be avoided.

**Comment by Samuell1** [comment] 2019-01-29 09:43
Duplicate of #1759

**Closed by Samuell1** 2019-01-29 09:43 UTC
