### ISSUE TITLE
 [mdTable] mdTablePagination : Computed property "subTotal" was assigned to but it has no setter.

### ISSUE THREAD

**Issue by alexMugen** [vuematerial/vue-material#959] opened 2017-08-09 13:32 UTC
Hello, 

Since i update vue material (^0.7.1 ), i have an error in my console : 
```
Computed property "subTotal" was assigned to but it has no setter.

found in

---> <MdTablePagination>
       <MdCard>
         <MdTableCard>
```

I don't understand because i didn't use subTotal property in my code

Thank you for your help 
Alex

**Comment by wandroll** [comment] 2017-08-09 15:10
Probably a duplicate of #943 . There is this PR #915  that should resolve your bug.

**Closed** 2017-08-09 15:26 UTC

**Comment by alexMugen** [comment] 2017-08-10 08:16
ok thank you @wandroll
