### ISSUE TITLE
[MdDatepicker] Multiple Vue Warn Messages

### ISSUE THREAD

**Issue by sl-digital** [vuematerial/vue-material#1437] opened 2018-01-24 20:39 UTC
### Steps to reproduce

using "vue-material" : "1.0.0-beta-7"

1) Import and use MdDatepicker with defaults in Vue template.
2) Build in Webpack and load page.
3) On click MdDatepicker opens with multiple console errors

### Which browser?

All browsers tested except Firefox where the Datepicker defaults to the system.

### What is expected?

No console errors.

### What is actually happening?

[Vue warn]: Invalid prop: type check failed for prop "mdDate". Expected Date, got String.
[Vue warn]: Duplicate keys detected: '1'. This may cause an update error.

**Comment by Samuell1** [comment] 2018-01-24 21:13
1. Dont use `string` use `null` as empty value.
2. Duplicate of #1376

**Closed** 2018-01-24 21:16 UTC

**Comment by sl-digital** [comment] 2018-01-24 21:22
Where is the fix from #1376?

**Comment by Samuell1** [comment] 2018-01-24 21:25
@sl-digital in dev branch
