### ISSUE TITLE
[Feature Request] - Autocomplete Plugin

### ISSUE THREAD

**Issue by kgrosvenor** [vuematerial/vue-material#651] opened 2017-03-30 19:25 UTC
May i suggest an auto complete plugin?  💯

**Comment by Samuell1** [comment] 2017-03-30 20:07
https://github.com/marcosmoura/vue-material/pull/644

**Comment by Morgul** [comment] 2017-06-21 15:40
Duplicate of #644.

**Closed by Morgul** 2017-06-21 15:40 UTC
Labels: duplicated, new component, request
