### ISSUE TITLE
[MdMenu] Scrolling issue

### ISSUE THREAD

**Issue by knatalia92** [vuematerial/vue-material#1694] opened 2018-04-26 12:02 UTC
### Steps to reproduce

Go to https://vuematerial.io/components/menu, open one of the menus and scroll the page

### Which browser?
Chrome/Firefox/Edge
Vue Material 1.0.0-beta-8

### What is expected?

When menu is opened, scrolling is prevented as in Vue Material 0.8.1 or menu content hides when user reaches its boundaries

### What is actually happening?

After reach top/bottom menu's boundary, the menu is moving with user

**Comment by Samuell1** [comment] 2018-04-26 12:06
Duplicate of #1330

**Closed by Samuell1** 2018-04-26 12:06 UTC
