### ISSUE TITLE
RTL Components needed

### ISSUE THREAD

**Issue by Hkh12** [vuematerial/vue-material#1594] opened 2018-03-11 20:06 UTC
Hi
I'm working on a big project and I want to build it with vuematerial, and I need __RTL__ components.
This solves some problems: 
```html
<body dir='rtl'>
```
But some components (like tabs and progress spinners) don't perform well.
So, Should I wait for v1.0.0?

Thanks ;) 
and sorry for my bad English

**Comment by Samuell1** [comment] 2018-03-11 20:46
Yes, RTL is on roadmap https://github.com/vuematerial/vue-material/issues/1081

**Comment by Samuell1** [comment] 2018-03-12 10:44
Duplicate of #80

**Closed by Samuell1** 2018-03-12 10:44 UTC
Labels: question
