### ISSUE TITLE
Unknown custom element: <md-table-toolbar>

### ISSUE THREAD

**Issue by codetrash** [vuematerial/vue-material#1181] opened 2017-11-20 10:00 UTC
installed it via npm 
```
npm install vue-material@beta --save
```
and md-table-toolbar component is not there. 

Onother issue is When I try to run the app, this error show up

![screenshot from 2017-11-20 17-33-26](https://user-images.githubusercontent.com/3906229/33014226-34a1b47c-ce19-11e7-8229-c7e77eb0c5e0.png)

**Comment by Samuell1** [comment] 2017-11-20 10:42
What is your code?

**Comment by codetrash** [comment] 2017-11-21 02:55
what i did:

1. I already have the old version installed
2. I want the new one so I installed it without removing the old one first
```
npm install vue-material@beta --save
```
3. And those issues appeared
4. I tried to remove them all and fresh install 
```
npm uninstall vue-material --save
npm uninstall vue-material@beta --save

npm install vue-material@beta --save
```
still got the same error
5. so I decided to install the old version again, it works

this might have smth to do with this issue  [regeneratorRuntime is not defined](https://github.com/vuematerial/vue-material/issues/1182)

**Comment by Samuell1** [comment] 2017-11-21 08:05
Yes it can be. What is your setup? Do you using vue-cli webpack template?

**Comment by codetrash** [comment] 2017-11-21 10:11
I use webpack template

**Comment by Samuell1** [comment] 2017-11-23 20:43
And version of Vue? Because new Vue Material needs Vue 2.5+

**Comment by marcosmoura** [comment] 2017-11-24 15:06
I will fix this ASAP

**Comment by doccom-applibs** [comment] 2017-12-04 09:15
Also experiencing this with a Webpack build, will move back to the old version in the interim.

**Comment by Samuell1** [comment] 2018-01-04 13:03
Duplicate of #1182

**Closed by Samuell1** 2018-01-04 13:03 UTC
Labels: bug
