### ISSUE TITLE
 [mdList] md-list-expand inside a dialog box are open by default

### ISSUE THREAD

**Issue by arnoldmq** [vuematerial/vue-material#686] opened 2017-04-15 13:38 UTC
When putting a list with expandable items inside a dialog box, the expandable items are open automatically, and some of those item in the expand element go under the main list items

Steps to reproduce
- create a dialog box,
-put list with expand items inside,
-make dialog box big enough that the list will fit in it with the expandable items open,
-open dialog box
-now that expandable items are open automatically 

Which browser?
chrome , ie

What is expected?
md-list-expand remain close when dialog is open

What is actually happening?
md-list-expand are open when dialog is open

Reproduction Link
http://codepen.io/anon/pen/dWobzK
(to see the issue make the result window in codepen bigger than it usually , if the md-dialog is small then the issue doesnt show, its mostly when the dialog box is bigger)

**Comment by coppee** [comment] 2017-05-12 09:59
Any clue ?

**Comment by vizv** [comment] 2017-07-13 19:19
Check `margin-bottom` of `md-list-expand`, it gives `0` instead of the `scrollHeight` of `md-list-expand`, and that's why it looks like already expanded on open.

I have a similar issue for the `margin-bottom` of `md-list-expand` may relate to your problem. A PR should come soon.

**Comment by mlg-ipleic** [comment] 2017-09-17 16:43
Anyone found solution to this, latest release is not working for me :/ still reproducible

**Comment by vizv** [comment] 2017-09-18 14:35
Well, PR #911 is a little bit different case. Could you guys check `active` state of `md-list-expand`. I think it might be the `active` state is somehow be set to `true`.

**Comment by gywgithub** [comment] 2017-09-22 05:50
I have the same problem.  
`md-liste-expand ` opens automatically
version: 0.7.5 
Code snippet: 
~~~

 <div id="app"> 
  <div>
    <md-button class="md-warn" @click.native="showCard">click</md-button>
    <md-card class="my-card" v-show="cardStatus">
      <md-list>
        <md-list-item>
          <md-icon>whatshot</md-icon>
          <span>News</span>

          <md-list-expand>
            <md-list>
              <md-list-item class="md-inset">World</md-list-item>
              <md-list-item class="md-inset">Americas</md-list-item>
              <md-list-item class="md-inset">Europe</md-list-item>
            </md-list>
          </md-list-expand>
        </md-list-item>
      </md-list>
    </md-card>
  </div>
</div>


<style>
.my-card {
 width: 200px;
}
</style>

<script>
Vue.use(VueMaterial)

var App = new Vue({
  el: '#app',
    data: {
      cardStatus: false
    },
    methods: { 
      showCard() {
        this.cardStatus = true;
      }
    
    }
})
<script>
~~~

**Comment by vizv** [comment] 2017-09-22 17:48
@gywgithub I just checked, on button clicked `md-list-expand` has `style="margin-bottom: 0;"` which cause the list looks like expanded. I'll look into this issue later.

**Comment by vizv** [comment] 2017-09-22 18:11
I found the problem:

When the page loads, `margin-bottom` was set to its height:

```js
          'margin-bottom': this.height
```
[mdListItemExpand.vue Line 49](https://github.com/vuematerial/vue-material/blob/28e73c7d20029affcf1ff3881e7024e241d56ab7/src/components/mdList/mdListItemExpand.vue#L49)

and the height was calculated from:

```js
          this.height = -this.$refs.expand.scrollHeight + 'px';
```

[mdListItemExpand.vue Line 67](https://github.com/vuematerial/vue-material/blob/28e73c7d20029affcf1ff3881e7024e241d56ab7/src/components/mdList/mdListItemExpand.vue#L67)

However, in a dialog the element has a style of `display: none` at the time when page loads, and thus `this.height` is calculated to `0px`, and `margin-bottom` is set to `0` initially, and the list appeared to be expanded by default.

I'm thinking with a solution to solve this right now.

**Comment by vizv** [comment] 2017-09-22 18:19
@gywgithub actually, if you change `v-show` to `v-if`, the problem will be solved.

**Comment by vizv** [comment] 2017-09-22 18:40
@arnoldmq I can't fix it due to current `mdDialog` implementation.

But one (ugly?) hack I can think of is:

add a line to `openDialog(ref)` method:

```js
      document.querySelectorAll('.md-list-item-expand').forEach((el) => { el.__vue__.calculatePadding() })
```

**Comment by gywgithub** [comment] 2017-09-24 09:49
@vizv  
Thank you very much for the perfect solution to my problems .

**Comment by profoX** [comment] 2017-11-20 00:47
Also had this problem. Thanks vizv, you way works, but it gave me another idea. With your solution, the items close when the dialog opens, I would like them closed without any effect on opening the dialog. So I came up with this solution:

a dialogShown data property which I toggle to true on opening a dialog and false on closing a dialog, and then I use v-if="dialogShown" on the md-list to force a render. Seems to work!

Could also fix the problem with md-tabs in an md-dialog (I also had this problem).

**Comment by Samuell1** [comment] 2017-11-23 20:34
Closing this issue as our focus is on the new 1.0.0 version.

**Closed by Samuell1** 2017-11-23 20:34 UTC
Labels: bug
