### ISSUE TITLE
md-[breakpoint]-hide / md-[breakpoint]-size-[amount] not working

### ISSUE THREAD

**Issue by warren10hk** [vuematerial/vue-material#1380] opened 2018-01-07 15:21 UTC
When I am using Chrome,

all the md-large- / md-xlarge- are not working.

Medium, small and xsmall works well.

**Comment by Samuell1** [comment] 2018-01-07 16:04
Duplicate of #1242

**Closed by Samuell1** 2018-01-07 16:04 UTC
